// Package client provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.0 DO NOT EDIT.
package client

import (
	"encoding/json"
	"fmt"
	"time"

	"github.com/oapi-codegen/runtime"
)

// Defines values for BackupStatusConditionsStatus.
const (
	BackupStatusConditionsStatusFalse   BackupStatusConditionsStatus = "False"
	BackupStatusConditionsStatusTrue    BackupStatusConditionsStatus = "True"
	BackupStatusConditionsStatusUnknown BackupStatusConditionsStatus = "Unknown"
)

// Defines values for BackupStatusExecutionMode.
const (
	BackupStatusExecutionModeJob             BackupStatusExecutionMode = "Job"
	BackupStatusExecutionModeProviderManaged BackupStatusExecutionMode = "ProviderManaged"
)

// Defines values for BackupClassSpecExecutionMode.
const (
	BackupClassSpecExecutionModeJob             BackupClassSpecExecutionMode = "Job"
	BackupClassSpecExecutionModeProviderManaged BackupClassSpecExecutionMode = "ProviderManaged"
)

// Defines values for BackupClassStatusConditionsStatus.
const (
	BackupClassStatusConditionsStatusFalse   BackupClassStatusConditionsStatus = "False"
	BackupClassStatusConditionsStatusTrue    BackupClassStatusConditionsStatus = "True"
	BackupClassStatusConditionsStatusUnknown BackupClassStatusConditionsStatus = "Unknown"
)

// Defines values for BackupStorageSpecType.
const (
	BackupStorageSpecTypeS3 BackupStorageSpecType = "s3"
)

// Defines values for InstanceStatusConditionsStatus.
const (
	InstanceStatusConditionsStatusFalse   InstanceStatusConditionsStatus = "False"
	InstanceStatusConditionsStatusTrue    InstanceStatusConditionsStatus = "True"
	InstanceStatusConditionsStatusUnknown InstanceStatusConditionsStatus = "Unknown"
)

// Defines values for InstanceStatusPhase.
const (
	InstanceStatusPhaseFailed       InstanceStatusPhase = "Failed"
	InstanceStatusPhaseInitializing InstanceStatusPhase = "Initializing"
	InstanceStatusPhasePending      InstanceStatusPhase = "Pending"
	InstanceStatusPhaseProvisioning InstanceStatusPhase = "Provisioning"
	InstanceStatusPhaseReady        InstanceStatusPhase = "Ready"
	InstanceStatusPhaseRestoring    InstanceStatusPhase = "Restoring"
	InstanceStatusPhaseResuming     InstanceStatusPhase = "Resuming"
	InstanceStatusPhaseSuspended    InstanceStatusPhase = "Suspended"
	InstanceStatusPhaseSuspending   InstanceStatusPhase = "Suspending"
	InstanceStatusPhaseTerminating  InstanceStatusPhase = "Terminating"
	InstanceStatusPhaseUpdating     InstanceStatusPhase = "Updating"
)

// Defines values for MonitoringConfigSpecType.
const (
	MonitoringConfigSpecTypePmm MonitoringConfigSpecType = "pmm"
)

// Defines values for ProviderStatusConditionsStatus.
const (
	ProviderStatusConditionsStatusFalse   ProviderStatusConditionsStatus = "False"
	ProviderStatusConditionsStatusTrue    ProviderStatusConditionsStatus = "True"
	ProviderStatusConditionsStatusUnknown ProviderStatusConditionsStatus = "Unknown"
)

// Defines values for RestoreSpecDataSourcePitrType.
const (
	RestoreSpecDataSourcePitrTypeDate   RestoreSpecDataSourcePitrType = "date"
	RestoreSpecDataSourcePitrTypeLatest RestoreSpecDataSourcePitrType = "latest"
)

// Defines values for RestoreStatusConditionsStatus.
const (
	RestoreStatusConditionsStatusFalse   RestoreStatusConditionsStatus = "False"
	RestoreStatusConditionsStatusTrue    RestoreStatusConditionsStatus = "True"
	RestoreStatusConditionsStatusUnknown RestoreStatusConditionsStatus = "Unknown"
)

// Defines values for RestoreStatusExecutionMode.
const (
	RestoreStatusExecutionModeJob             RestoreStatusExecutionMode = "Job"
	RestoreStatusExecutionModeProviderManaged RestoreStatusExecutionMode = "ProviderManaged"
)

// Backup Backup is the Schema for the backups API.
type Backup struct {
	// ApiVersion APIVersion defines the versioned schema of this representation of an object.
	// Servers should convert recognized schemas to the latest internal value, and
	// may reject unrecognized values.
	// More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
	ApiVersion *string `json:"apiVersion,omitempty"`

	// Kind Kind is a string value representing the REST resource this object represents.
	// Servers may infer this from the endpoint the client submits requests to.
	// Cannot be updated.
	// In CamelCase.
	// More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
	Kind     *string                 `json:"kind,omitempty"`
	Metadata *map[string]interface{} `json:"metadata,omitempty"`

	// Spec BackupSpec defines the desired state of Backup.
	Spec struct {
		// BackupClassName BackupClassName is the BackupClass that defines how this Backup is
		// executed. The class's executionMode controls the runtime path: Job
		// classes are reconciled by the in-cluster Backup job controller;
		// ProviderManaged classes are reconciled by the provider's runtime.
		BackupClassName string `json:"backupClassName"`

		// Config Config is the backup-time configuration validated against the
		// BackupClass's .spec.config.openAPIV3Schema.
		Config *map[string]interface{} `json:"config,omitempty"`

		// DeletionPolicy DeletionPolicy controls what happens to the underlying backup data
		// (e.g., the object stored in S3) when this Backup CR is deleted.
		// Delete (default) instructs the provider to remove both the
		// engine-native backup resource and the data in the configured
		// BackupStorage. Retain instructs the provider to remove the
		// engine-native backup resource but to leave the underlying data in
		// place, so it can be recovered later out-of-band.
		//
		// The field is mutable on a live Backup but is frozen once deletion
		// has started: switching policies after .metadata.deletionTimestamp
		// has been set is rejected so the cleanup path cannot race with
		// itself.
		DeletionPolicy interface{} `json:"deletionPolicy,omitempty"`

		// InstanceName InstanceName is the name of the Instance to back up. The Instance must
		// live in the same namespace as this Backup.
		InstanceName string `json:"instanceName"`

		// ScheduleName ScheduleName, when set, identifies the InstanceBackupSchedule that
		// produced this Backup. Backups created via the API or `kubectl apply`
		// leave this field empty (on-demand). The provider's mirroring loop
		// sets it when surfacing operator-produced scheduled backups as Backup
		// CRs.
		ScheduleName *string `json:"scheduleName,omitempty"`

		// StorageName StorageName references a BackupStorage in the same namespace that
		// defines where the backup data is written. For ProviderManaged classes
		// the referenced storage must already be registered on the Instance via
		// .spec.backup.storages so the engine can write to it.
		StorageName string `json:"storageName"`
	} `json:"spec"`

	// Status BackupStatus defines the observed state of Backup.
	Status *struct {
		// CompletedAt CompletedAt is the time when the backup completed successfully.
		CompletedAt *time.Time `json:"completedAt,omitempty"`
		Conditions  *[]struct {
			// LastTransitionTime lastTransitionTime is the last time the condition transitioned from one status to another.
			// This should be when the underlying condition changed.  If that is not known, then using the time when the API field changed is acceptable.
			LastTransitionTime time.Time `json:"lastTransitionTime"`

			// Message message is a human readable message indicating details about the transition.
			// This may be an empty string.
			Message string `json:"message"`

			// ObservedGeneration observedGeneration represents the .metadata.generation that the condition was set based upon.
			// For instance, if .metadata.generation is currently 12, but the .status.conditions[x].observedGeneration is 9, the condition is out of date
			// with respect to the current state of the instance.
			ObservedGeneration *int64 `json:"observedGeneration,omitempty"`

			// Reason reason contains a programmatic identifier indicating the reason for the condition's last transition.
			// Producers of specific condition types may define expected values and meanings for this field,
			// and whether the values are considered a guaranteed API.
			// The value should be a CamelCase string.
			// This field may not be empty.
			Reason string `json:"reason"`

			// Status status of the condition, one of True, False, Unknown.
			Status BackupStatusConditionsStatus `json:"status"`

			// Type type of condition in CamelCase or in foo.example.com/CamelCase.
			Type string `json:"type"`
		} `json:"conditions,omitempty"`

		// ExecutionMode ExecutionMode is the resolved execution mode at the time the Backup
		// started. Recorded for observability.
		ExecutionMode *BackupStatusExecutionMode `json:"executionMode,omitempty"`

		// JobName JobName is the reference to the Job that is running the backup.
		// Populated only for Job classes.
		JobName *string `json:"jobName,omitempty"`

		// LastObservedGeneration LastObservedGeneration is the last observed generation of the Backup CR.
		LastObservedGeneration *int64 `json:"lastObservedGeneration,omitempty"`

		// Message Message is a human-readable message about the current state.
		Message *string `json:"message,omitempty"`

		// OperatorBackupRef OperatorBackupRef points at the operator-native backup resource the
		// provider created (e.g., PerconaServerMongoDBBackup). Populated only
		// for ProviderManaged classes.
		OperatorBackupRef *struct {
			// ApiGroup APIGroup is the group for the resource being referenced.
			// If APIGroup is not specified, the specified Kind must be in the core API group.
			// For any other third-party types, APIGroup is required.
			ApiGroup *string `json:"apiGroup,omitempty"`

			// Kind Kind is the type of resource being referenced
			Kind string `json:"kind"`

			// Name Name is the name of resource being referenced
			Name string `json:"name"`
		} `json:"operatorBackupRef,omitempty"`

		// StartedAt StartedAt is the time when the backup started.
		StartedAt *time.Time `json:"startedAt,omitempty"`

		// State State is the current state of the backup.
		State *string `json:"state,omitempty"`
	} `json:"status,omitempty"`
}

// BackupStatusConditionsStatus status of the condition, one of True, False, Unknown.
type BackupStatusConditionsStatus string

// BackupStatusExecutionMode ExecutionMode is the resolved execution mode at the time the Backup
// started. Recorded for observability.
type BackupStatusExecutionMode string

// BackupClass BackupClass is the Schema for the backupclasses API
type BackupClass struct {
	// ApiVersion APIVersion defines the versioned schema of this representation of an object.
	// Servers should convert recognized schemas to the latest internal value, and
	// may reject unrecognized values.
	// More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
	ApiVersion *string `json:"apiVersion,omitempty"`

	// Kind Kind is a string value representing the REST resource this object represents.
	// Servers may infer this from the endpoint the client submits requests to.
	// Cannot be updated.
	// In CamelCase.
	// More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
	Kind     *string                 `json:"kind,omitempty"`
	Metadata *map[string]interface{} `json:"metadata,omitempty"`

	// Spec BackupClassSpec defines the desired state of BackupClass.
	Spec struct {
		// Config Config contains the OpenAPI v3 schema describing the backup-time
		// configuration accepted by this class. Backup.spec.config is validated
		// against this schema.
		Config *struct {
			// OpenAPIV3Schema OpenAPIV3Schema is the OpenAPI v3 schema of the backup class.
			OpenAPIV3Schema interface{} `json:"openAPIV3Schema,omitempty"`
		} `json:"config,omitempty"`

		// Description Description is the description of the backup class.
		Description *string `json:"description,omitempty"`

		// DisplayName DisplayName is a human-readable name for the backup class.
		DisplayName *string `json:"displayName,omitempty"`

		// ExecutionMode ExecutionMode selects between job-based and provider-managed execution.
		ExecutionMode BackupClassSpecExecutionMode `json:"executionMode"`

		// InstanceConstraints InstanceConstraints defines compatibility requirements that must be
		// satisfied by an Instance before this backup class can be used with it.
		InstanceConstraints *struct {
			// RequiredFields RequiredFields contains a list of fields that must be set in the Instance spec.
			// Each key is a JSON path expressions that points to a field in the Instance spec.
			// For example, ".spec.engine.type" or ".spec.dataSource.dataImport.config.someField".
			RequiredFields *[]string `json:"requiredFields,omitempty"`
		} `json:"instanceConstraints,omitempty"`

		// Job Job contains execution detail for ExecutionMode="Job". Must be unset
		// when ExecutionMode is "ProviderManaged".
		Job *struct {
			// CleanupJobSpec CleanupJobSpec is the optional specification of a cleanup job that runs
			// when the parent Backup or Restore CR is deleted.
			CleanupJobSpec *struct {
				// Command Command is the command to run the backup class.
				Command *[]string `json:"command,omitempty"`

				// Image Image is the image of the backup class.
				Image *string `json:"image,omitempty"`
			} `json:"cleanupJobSpec,omitempty"`

			// ClusterPermissions ClusterPermissions are cluster-scoped PolicyRules granted via a
			// generated ClusterRole and ClusterRoleBinding.
			ClusterPermissions *[]struct {
				// ApiGroups APIGroups is the name of the APIGroup that contains the resources.  If multiple API groups are specified, any action requested against one of
				// the enumerated resources in any API group will be allowed. "" represents the core API group and "*" represents all API groups.
				ApiGroups *[]string `json:"apiGroups,omitempty"`

				// NonResourceURLs NonResourceURLs is a set of partial urls that a user should have access to.  *s are allowed, but only as the full, final step in the path
				// Since non-resource URLs are not namespaced, this field is only applicable for ClusterRoles referenced from a ClusterRoleBinding.
				// Rules can either apply to API resources (such as "pods" or "secrets") or non-resource URL paths (such as "/api"),  but not both.
				NonResourceURLs *[]string `json:"nonResourceURLs,omitempty"`

				// ResourceNames ResourceNames is an optional white list of names that the rule applies to.  An empty set means that everything is allowed.
				ResourceNames *[]string `json:"resourceNames,omitempty"`

				// Resources Resources is a list of resources this rule applies to. '*' represents all resources.
				Resources *[]string `json:"resources,omitempty"`

				// Verbs Verbs is a list of Verbs that apply to ALL the ResourceKinds contained in this rule. '*' represents all verbs.
				Verbs []string `json:"verbs"`
			} `json:"clusterPermissions,omitempty"`

			// JobSpec JobSpec is the specification of the backup or restore job.
			JobSpec struct {
				// Command Command is the command to run the backup class.
				Command *[]string `json:"command,omitempty"`

				// Image Image is the image of the backup class.
				Image *string `json:"image,omitempty"`
			} `json:"jobSpec"`

			// Permissions Permissions are namespace-scoped PolicyRules granted to the job pod via
			// a generated Role and RoleBinding.
			Permissions *[]struct {
				// ApiGroups APIGroups is the name of the APIGroup that contains the resources.  If multiple API groups are specified, any action requested against one of
				// the enumerated resources in any API group will be allowed. "" represents the core API group and "*" represents all API groups.
				ApiGroups *[]string `json:"apiGroups,omitempty"`

				// NonResourceURLs NonResourceURLs is a set of partial urls that a user should have access to.  *s are allowed, but only as the full, final step in the path
				// Since non-resource URLs are not namespaced, this field is only applicable for ClusterRoles referenced from a ClusterRoleBinding.
				// Rules can either apply to API resources (such as "pods" or "secrets") or non-resource URL paths (such as "/api"),  but not both.
				NonResourceURLs *[]string `json:"nonResourceURLs,omitempty"`

				// ResourceNames ResourceNames is an optional white list of names that the rule applies to.  An empty set means that everything is allowed.
				ResourceNames *[]string `json:"resourceNames,omitempty"`

				// Resources Resources is a list of resources this rule applies to. '*' represents all resources.
				Resources *[]string `json:"resources,omitempty"`

				// Verbs Verbs is a list of Verbs that apply to ALL the ResourceKinds contained in this rule. '*' represents all verbs.
				Verbs []string `json:"verbs"`
			} `json:"permissions,omitempty"`
		} `json:"job,omitempty"`

		// ProviderManaged ProviderManaged contains hints for ExecutionMode="ProviderManaged". The
		// schema is intentionally open: providers may surface capability
		// information (e.g., whether PITR is supported, schedule expression
		// dialect) without forcing a CRD change. Must be unset when
		// ExecutionMode is "Job".
		ProviderManaged *struct {
			// SupportsPITR SupportsPITR indicates whether this class supports point-in-time recovery.
			// Used by Restore validation when Restore.spec.dataSource.pitr is set.
			SupportsPITR *bool `json:"supportsPITR,omitempty"`
		} `json:"providerManaged,omitempty"`

		// RestoreConfig RestoreConfig contains the OpenAPI v3 schema describing the restore-time
		// configuration accepted by this class. Restore.spec.config is validated
		// against this schema.
		RestoreConfig *struct {
			// OpenAPIV3Schema OpenAPIV3Schema is the OpenAPI v3 schema of the backup class.
			OpenAPIV3Schema interface{} `json:"openAPIV3Schema,omitempty"`
		} `json:"restoreConfig,omitempty"`

		// RestoreJob RestoreJob contains execution detail for the restore job in
		// ExecutionMode="Job". Must be unset when ExecutionMode is
		// "ProviderManaged".
		RestoreJob *struct {
			// CleanupJobSpec CleanupJobSpec is the optional specification of a cleanup job that runs
			// when the parent Backup or Restore CR is deleted.
			CleanupJobSpec *struct {
				// Command Command is the command to run the backup class.
				Command *[]string `json:"command,omitempty"`

				// Image Image is the image of the backup class.
				Image *string `json:"image,omitempty"`
			} `json:"cleanupJobSpec,omitempty"`

			// ClusterPermissions ClusterPermissions are cluster-scoped PolicyRules granted via a
			// generated ClusterRole and ClusterRoleBinding.
			ClusterPermissions *[]struct {
				// ApiGroups APIGroups is the name of the APIGroup that contains the resources.  If multiple API groups are specified, any action requested against one of
				// the enumerated resources in any API group will be allowed. "" represents the core API group and "*" represents all API groups.
				ApiGroups *[]string `json:"apiGroups,omitempty"`

				// NonResourceURLs NonResourceURLs is a set of partial urls that a user should have access to.  *s are allowed, but only as the full, final step in the path
				// Since non-resource URLs are not namespaced, this field is only applicable for ClusterRoles referenced from a ClusterRoleBinding.
				// Rules can either apply to API resources (such as "pods" or "secrets") or non-resource URL paths (such as "/api"),  but not both.
				NonResourceURLs *[]string `json:"nonResourceURLs,omitempty"`

				// ResourceNames ResourceNames is an optional white list of names that the rule applies to.  An empty set means that everything is allowed.
				ResourceNames *[]string `json:"resourceNames,omitempty"`

				// Resources Resources is a list of resources this rule applies to. '*' represents all resources.
				Resources *[]string `json:"resources,omitempty"`

				// Verbs Verbs is a list of Verbs that apply to ALL the ResourceKinds contained in this rule. '*' represents all verbs.
				Verbs []string `json:"verbs"`
			} `json:"clusterPermissions,omitempty"`

			// JobSpec JobSpec is the specification of the backup or restore job.
			JobSpec struct {
				// Command Command is the command to run the backup class.
				Command *[]string `json:"command,omitempty"`

				// Image Image is the image of the backup class.
				Image *string `json:"image,omitempty"`
			} `json:"jobSpec"`

			// Permissions Permissions are namespace-scoped PolicyRules granted to the job pod via
			// a generated Role and RoleBinding.
			Permissions *[]struct {
				// ApiGroups APIGroups is the name of the APIGroup that contains the resources.  If multiple API groups are specified, any action requested against one of
				// the enumerated resources in any API group will be allowed. "" represents the core API group and "*" represents all API groups.
				ApiGroups *[]string `json:"apiGroups,omitempty"`

				// NonResourceURLs NonResourceURLs is a set of partial urls that a user should have access to.  *s are allowed, but only as the full, final step in the path
				// Since non-resource URLs are not namespaced, this field is only applicable for ClusterRoles referenced from a ClusterRoleBinding.
				// Rules can either apply to API resources (such as "pods" or "secrets") or non-resource URL paths (such as "/api"),  but not both.
				NonResourceURLs *[]string `json:"nonResourceURLs,omitempty"`

				// ResourceNames ResourceNames is an optional white list of names that the rule applies to.  An empty set means that everything is allowed.
				ResourceNames *[]string `json:"resourceNames,omitempty"`

				// Resources Resources is a list of resources this rule applies to. '*' represents all resources.
				Resources *[]string `json:"resources,omitempty"`

				// Verbs Verbs is a list of Verbs that apply to ALL the ResourceKinds contained in this rule. '*' represents all verbs.
				Verbs []string `json:"verbs"`
			} `json:"permissions,omitempty"`
		} `json:"restoreJob,omitempty"`

		// SupportedProviders SupportedProviders is the list of provider names that this backup class
		// supports. The Instance.spec.provider must appear in this list for the
		// class to be usable on that Instance.
		SupportedProviders *[]string `json:"supportedProviders,omitempty"`
	} `json:"spec"`

	// Status BackupClassStatus defines the observed state of BackupClass.
	Status *struct {
		Conditions *[]struct {
			// LastTransitionTime lastTransitionTime is the last time the condition transitioned from one status to another.
			// This should be when the underlying condition changed.  If that is not known, then using the time when the API field changed is acceptable.
			LastTransitionTime time.Time `json:"lastTransitionTime"`

			// Message message is a human readable message indicating details about the transition.
			// This may be an empty string.
			Message string `json:"message"`

			// ObservedGeneration observedGeneration represents the .metadata.generation that the condition was set based upon.
			// For instance, if .metadata.generation is currently 12, but the .status.conditions[x].observedGeneration is 9, the condition is out of date
			// with respect to the current state of the instance.
			ObservedGeneration *int64 `json:"observedGeneration,omitempty"`

			// Reason reason contains a programmatic identifier indicating the reason for the condition's last transition.
			// Producers of specific condition types may define expected values and meanings for this field,
			// and whether the values are considered a guaranteed API.
			// The value should be a CamelCase string.
			// This field may not be empty.
			Reason string `json:"reason"`

			// Status status of the condition, one of True, False, Unknown.
			Status BackupClassStatusConditionsStatus `json:"status"`

			// Type type of condition in CamelCase or in foo.example.com/CamelCase.
			Type string `json:"type"`
		} `json:"conditions,omitempty"`
	} `json:"status,omitempty"`
}

// BackupClassSpecExecutionMode ExecutionMode selects between job-based and provider-managed execution.
type BackupClassSpecExecutionMode string

// BackupClassStatusConditionsStatus status of the condition, one of True, False, Unknown.
type BackupClassStatusConditionsStatus string

// BackupClassList BackupClassList is an object that contains the list of the existing backupclasss.
type BackupClassList struct {
	// ApiVersion APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
	ApiVersion *string        `json:"apiVersion,omitempty"`
	Items      *[]BackupClass `json:"items,omitempty"`

	// Kind Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
	Kind     *string `json:"kind,omitempty"`
	Metadata *struct {
		// Name Name must be unique within a namespace. Is required when creating resources, although some resources may allow a client to request the generation of an appropriate name automatically. Name is primarily intended for creation idempotence and configuration definition. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names#names
		Name *string `json:"name,omitempty"`
	} `json:"metadata,omitempty"`
}

// BackupList BackupList is an object that contains the list of the existing backups.
type BackupList struct {
	// ApiVersion APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
	ApiVersion *string   `json:"apiVersion,omitempty"`
	Items      *[]Backup `json:"items,omitempty"`

	// Kind Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
	Kind     *string `json:"kind,omitempty"`
	Metadata *struct {
		// Name Name must be unique within a namespace. Is required when creating resources, although some resources may allow a client to request the generation of an appropriate name automatically. Name is primarily intended for creation idempotence and configuration definition. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names#names
		Name *string `json:"name,omitempty"`

		// Namespace Namespace defines the space within which each name must be unique. An empty namespace is equivalent to the "default" namespace, but "default" is the canonical representation. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/namespaces
		Namespace *string `json:"namespace,omitempty"`
	} `json:"metadata,omitempty"`
}

// BackupStorage BackupStorage is the Schema for the backupstorages API.
type BackupStorage struct {
	// ApiVersion APIVersion defines the versioned schema of this representation of an object.
	// Servers should convert recognized schemas to the latest internal value, and
	// may reject unrecognized values.
	// More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
	ApiVersion *string `json:"apiVersion,omitempty"`

	// Kind Kind is a string value representing the REST resource this object represents.
	// Servers may infer this from the endpoint the client submits requests to.
	// Cannot be updated.
	// In CamelCase.
	// More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
	Kind     *string                 `json:"kind,omitempty"`
	Metadata *map[string]interface{} `json:"metadata,omitempty"`

	// Spec BackupStorageSpec defines the desired state of a BackupStorage.
	//
	// A BackupStorage is a reusable, namespaced reference to an object store
	// (today only S3-compatible) plus the credentials needed to talk to it.
	// It is referenced by name from:
	//
	//   - Instance.spec.backup.storages[].storageRef
	//   - Backup.spec.storageName
	//   - Restore.spec.dataSource.external.storageName
	//
	// Decoupling storage from individual Backup CRs makes provider-managed
	// backups (e.g. PBM, pgBackRest) practical: the provider can register a
	// fixed set of storages on the engine without recomputing them from a
	// dynamic list of Backup CRs.
	Spec struct {
		// S3 S3 contains S3-compatible storage configuration.
		// Required when Type is "s3".
		S3 *struct {
			// AccessKeyId AccessKeyID is a write-only convenience input. When set, a webhook
			// stores it in the Secret named by CredentialsSecretName and clears
			// this field. It is never persisted on the BackupStorage object.
			AccessKeyId *string `json:"accessKeyId,omitempty"`

			// Bucket Bucket is the name of the S3 bucket.
			Bucket string `json:"bucket"`

			// CredentialsSecretName CredentialsSecretName is the name of the Secret in the same namespace
			// that holds the AWS_ACCESS_KEY_ID and AWS_SECRET_ACCESS_KEY keys.
			CredentialsSecretName string `json:"credentialsSecretName"`

			// EndpointURL EndpointURL is the endpoint URL of the S3-compatible service.
			EndpointURL string `json:"endpointURL"`

			// ForcePathStyle ForcePathStyle forces path-style URLs (bucket name in the path
			// instead of the host). Defaults to false.
			ForcePathStyle *bool `json:"forcePathStyle,omitempty"`

			// Region Region is the region of the S3 bucket.
			Region string `json:"region"`

			// SecretAccessKey SecretAccessKey is a write-only convenience input. See AccessKeyID.
			SecretAccessKey *string `json:"secretAccessKey,omitempty"`

			// VerifyTLS VerifyTLS enables TLS certificate verification.
			// Defaults to true.
			VerifyTLS *bool `json:"verifyTLS,omitempty"`
		} `json:"s3,omitempty"`

		// Type Type is the object storage type. Today only "s3" is supported.
		Type BackupStorageSpecType `json:"type"`
	} `json:"spec"`

	// Status BackupStorageStatus defines the observed state of a BackupStorage.
	Status *map[string]interface{} `json:"status,omitempty"`
}

// BackupStorageSpecType Type is the object storage type. Today only "s3" is supported.
type BackupStorageSpecType string

// BackupStorageList BackupStorageList is an object that contains the list of the existing backupstorages.
type BackupStorageList struct {
	// ApiVersion APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
	ApiVersion *string          `json:"apiVersion,omitempty"`
	Items      *[]BackupStorage `json:"items,omitempty"`

	// Kind Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
	Kind     *string `json:"kind,omitempty"`
	Metadata *struct {
		// Name Name must be unique within a namespace. Is required when creating resources, although some resources may allow a client to request the generation of an appropriate name automatically. Name is primarily intended for creation idempotence and configuration definition. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names#names
		Name *string `json:"name,omitempty"`

		// Namespace Namespace defines the space within which each name must be unique. An empty namespace is equivalent to the "default" namespace, but "default" is the canonical representation. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/namespaces
		Namespace *string `json:"namespace,omitempty"`
	} `json:"metadata,omitempty"`
}

// Instance Instance is the Schema for the instances API
type Instance struct {
	// ApiVersion APIVersion defines the versioned schema of this representation of an object.
	// Servers should convert recognized schemas to the latest internal value, and
	// may reject unrecognized values.
	// More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
	ApiVersion *string `json:"apiVersion,omitempty"`

	// Kind Kind is a string value representing the REST resource this object represents.
	// Servers may infer this from the endpoint the client submits requests to.
	// Cannot be updated.
	// In CamelCase.
	// More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
	Kind     *string                 `json:"kind,omitempty"`
	Metadata *map[string]interface{} `json:"metadata,omitempty"`

	// Spec InstanceSpec defines the desired state of Instance
	Spec struct {
		// Backup Backup configures the backup feature for this Instance. When enabled,
		// the provider's reconciler is given the resolved BackupClass and storage
		// list so it can configure the engine accordingly (sidecars, agent
		// configuration, etc.). Required for ProviderManaged BackupClasses; Job
		// classes do not need an entry here because they read directly from
		// individual Backup CRs.
		Backup *struct {
			// ClassRef ClassRef references the BackupClass that the provider should use to
			// configure the engine. The class must have ExecutionMode=ProviderManaged
			// and list the Instance's provider in its SupportedProviders.
			ClassRef struct {
				// Name Name is the BackupClass name. BackupClasses are cluster-scoped.
				Name string `json:"name"`
			} `json:"classRef"`

			// Enabled Enabled toggles the backup feature for this Instance. When false the
			// runtime skips ConfigureBackup() and the rest of this struct is ignored.
			Enabled bool `json:"enabled"`

			// Pitr PITR enables and configures point-in-time recovery on the engine.
			// Requires the BackupClass to advertise PITR support via
			// .spec.providerManaged.
			Pitr *struct {
				// Config Config holds provider-specific PITR options. The schema is defined by
				// the BackupClass via .spec.providerManaged.
				Config *map[string]interface{} `json:"config,omitempty"`

				// Enabled Enabled toggles PITR.
				Enabled bool `json:"enabled"`

				// StorageName StorageName is the logical name of the storage (one of
				// .spec.backup.storages[].name) that PITR should write to.
				StorageName *string `json:"storageName,omitempty"`
			} `json:"pitr,omitempty"`

			// Schedules Schedules registers recurring backup tasks on the engine. Schedules
			// produce Backup CRs (via the provider's mirroring loop) using the
			// operator-native scheduler — the runtime never spawns CronJobs for
			// ProviderManaged BackupClasses.
			Schedules *[]struct {
				// Cron Cron is a standard 5-field cron expression. The provider may reject
				// expressions the engine does not support.
				Cron string `json:"cron"`

				// Enabled Enabled toggles the schedule. A disabled schedule is removed from
				// the engine without losing its definition on the Instance.
				Enabled bool `json:"enabled"`

				// Name Name uniquely identifies the schedule within the Instance. The
				// provider uses it as the schedule key on the engine and as the value
				// of Backup.spec.scheduleName on mirrored Backup CRs.
				Name string `json:"name"`

				// RetentionCopies RetentionCopies is the number of recent backups to keep for this
				// schedule. Zero (or unset) means "keep all". Negative values are
				// rejected.
				RetentionCopies *int32 `json:"retentionCopies,omitempty"`

				// StorageName StorageName references one of .spec.backup.storages[].name. Required.
				StorageName string `json:"storageName"`
			} `json:"schedules,omitempty"`

			// Storages Storages registers BackupStorages on the engine. Each entry maps a
			// logical name (visible to the engine and reused by Backup CRs via
			// .spec.storageName) to a BackupStorage resource.
			Storages *[]struct {
				// Main Main marks this storage as the engine's default. At most one storage
				// per Instance may be marked main.
				Main *bool `json:"main,omitempty"`

				// Name Name is the logical name the engine uses for this storage. It is also
				// the value that Backup CRs target via .spec.storageName.
				Name string `json:"name"`

				// StorageRef StorageRef references a BackupStorage in the same namespace.
				StorageRef struct {
					// Name Name of the referent.
					// This field is effectively required, but due to backwards compatibility is
					// allowed to be empty. Instances of this type with an empty value here are
					// almost certainly wrong.
					// More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names
					Name *string `json:"name,omitempty"`
				} `json:"storageRef"`
			} `json:"storages,omitempty"`
		} `json:"backup,omitempty"`

		// Components Components defines the component instances for this cluster.
		// The keys are component names (e.g., "engine", "proxy", "backupAgent").
		// Which components are valid depends on the selected topology.
		Components *map[string]struct {
			// Config Config specifies the component specific configuration.
			Config *struct {
				// ConfigMapRef LocalObjectReference contains enough information to let you locate the
				// referenced object inside the same namespace.
				ConfigMapRef *struct {
					// Name Name of the referent.
					// This field is effectively required, but due to backwards compatibility is
					// allowed to be empty. Instances of this type with an empty value here are
					// almost certainly wrong.
					// More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names
					Name *string `json:"name,omitempty"`
				} `json:"configMapRef,omitempty"`
				Key *string `json:"key,omitempty"`

				// SecretRef LocalObjectReference contains enough information to let you locate the
				// referenced object inside the same namespace.
				SecretRef *struct {
					// Name Name of the referent.
					// This field is effectively required, but due to backwards compatibility is
					// allowed to be empty. Instances of this type with an empty value here are
					// almost certainly wrong.
					// More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names
					Name *string `json:"name,omitempty"`
				} `json:"secretRef,omitempty"`
			} `json:"config,omitempty"`

			// CustomSpec CustomSpec provides an API for customising this component.
			// The API schema is defined by the provider's ComponentSchemas.
			CustomSpec *map[string]interface{} `json:"customSpec,omitempty"`

			// Image Image specifies an override for the image to use.
			// When unspecified, it is autmatically set from the ComponentVersions
			// based on the Version specified.
			Image *string `json:"image,omitempty"`

			// Name Name of the component.
			Name *string `json:"name,omitempty"`

			// Replicas Replicas specifies the number of replicas for this component.
			Replicas *int32 `json:"replicas,omitempty"`

			// Resources Resources requirements for this component.
			Resources *struct {
				// Claims Claims lists the names of resources, defined in spec.resourceClaims,
				// that are used by this container.
				//
				// This field depends on the
				// DynamicResourceAllocation feature gate.
				//
				// This field is immutable. It can only be set for containers.
				Claims *[]struct {
					// Name Name must match the name of one entry in pod.spec.resourceClaims of
					// the Pod where this field is used. It makes that resource available
					// inside a container.
					Name string `json:"name"`

					// Request Request is the name chosen for a request in the referenced claim.
					// If empty, everything from the claim is made available, otherwise
					// only the result of this request.
					Request *string `json:"request,omitempty"`
				} `json:"claims,omitempty"`

				// Limits Limits describes the maximum amount of compute resources allowed.
				// More info: https://kubernetes.io/docs/concepts/configuration/manage-resources-containers/
				Limits *map[string]Instance_Spec_Components_Resources_Limits_AdditionalProperties `json:"limits,omitempty"`

				// Requests Requests describes the minimum amount of compute resources required.
				// If Requests is omitted for a container, it defaults to Limits if that is explicitly specified,
				// otherwise to an implementation-defined value. Requests cannot exceed Limits.
				// More info: https://kubernetes.io/docs/concepts/configuration/manage-resources-containers/
				Requests *map[string]Instance_Spec_Components_Resources_Requests_AdditionalProperties `json:"requests,omitempty"`
			} `json:"resources,omitempty"`

			// Storage Storage requirements for this component.
			// For stateless components, this is an optional field.
			Storage *struct {
				Size         *Instance_Spec_Components_Storage_Size `json:"size,omitempty"`
				StorageClass *string                                `json:"storageClass,omitempty"`
			} `json:"storage,omitempty"`

			// Type Type of the component from the Provider.
			Type *string `json:"type,omitempty"`

			// Version Version of the component from ComponentVersions.
			Version *string `json:"version,omitempty"`
		} `json:"components,omitempty"`

		// Global Global contains provider-level configuration that applies to the entire cluster.
		// The schema for this field is defined by the provider's GlobalConfigSchema.
		Global *map[string]interface{} `json:"global,omitempty"`

		// Provider Provider is the name of the database provider (e.g., "psmdb", "postgresql").
		Provider *string `json:"provider,omitempty"`

		// Topology Topology defines the deployment topology and its configuration.
		Topology *struct {
			// Config Config contains topology-specific configuration.
			// The schema for this field is defined by the provider's TopologyDefinition.
			// Examples: shard count for sharded topology, replication factor, etc.
			Config *map[string]interface{} `json:"config,omitempty"`

			// Type Type is the topology name (e.g., "sharded", "replicaset").
			// The available topologies are defined by the provider.
			// If omitted, the provider's default topology is used.
			Type *string `json:"type,omitempty"`
		} `json:"topology,omitempty"`

		// Version Version selects a provider-defined version bundle, resolving compatible
		// versions for all components automatically. Per-component versions set
		// in Components take precedence over the bundle.
		// If omitted and the provider defines a default bundle, that bundle is used.
		Version *string `json:"version,omitempty"`
	} `json:"spec"`

	// Status InstanceStatus defines the observed state of Instance.
	Status *struct {
		// Components Components is the status of the components in the database cluster.
		Components *[]struct {
			Pods *[]struct {
				// Name Name of the referent.
				// This field is effectively required, but due to backwards compatibility is
				// allowed to be empty. Instances of this type with an empty value here are
				// almost certainly wrong.
				// More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names
				Name *string `json:"name,omitempty"`
			} `json:"pods,omitempty"`
			Ready *int32  `json:"ready,omitempty"`
			State *string `json:"state,omitempty"`
			Total *int32  `json:"total,omitempty"`
		} `json:"components,omitempty"`
		Conditions *[]struct {
			// LastTransitionTime lastTransitionTime is the last time the condition transitioned from one status to another.
			// This should be when the underlying condition changed.  If that is not known, then using the time when the API field changed is acceptable.
			LastTransitionTime time.Time `json:"lastTransitionTime"`

			// Message message is a human readable message indicating details about the transition.
			// This may be an empty string.
			Message string `json:"message"`

			// ObservedGeneration observedGeneration represents the .metadata.generation that the condition was set based upon.
			// For instance, if .metadata.generation is currently 12, but the .status.conditions[x].observedGeneration is 9, the condition is out of date
			// with respect to the current state of the instance.
			ObservedGeneration *int64 `json:"observedGeneration,omitempty"`

			// Reason reason contains a programmatic identifier indicating the reason for the condition's last transition.
			// Producers of specific condition types may define expected values and meanings for this field,
			// and whether the values are considered a guaranteed API.
			// The value should be a CamelCase string.
			// This field may not be empty.
			Reason string `json:"reason"`

			// Status status of the condition, one of True, False, Unknown.
			Status InstanceStatusConditionsStatus `json:"status"`

			// Type type of condition in CamelCase or in foo.example.com/CamelCase.
			Type string `json:"type"`
		} `json:"conditions,omitempty"`

		// ConnectionSecretRef ConnectionSecretRef is a reference to the Secret containing connection details.
		// The Secret is auto-generated by the provider-runtime reconciler with the name
		// "{instance-name}-conn" and owned by the Instance (auto-deleted on cleanup).
		//
		// The Secret uses well-known keys inspired by the Service Binding specification:
		//   - "type"     - Database type (e.g., "mongodb", "postgresql")
		//   - "provider" - Provider name (e.g., "percona-server-mongodb")
		//   - "host"     - Hostname or IP address
		//   - "port"     - Port number
		//   - "username" - Database username
		//   - "password" - Database password
		//   - "uri"      - Full connection URI including credentials
		ConnectionSecretRef *struct {
			// Name Name of the referent.
			// This field is effectively required, but due to backwards compatibility is
			// allowed to be empty. Instances of this type with an empty value here are
			// almost certainly wrong.
			// More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names
			Name *string `json:"name,omitempty"`
		} `json:"connectionSecretRef,omitempty"`

		// Phase Phase of the database cluster.
		Phase *InstanceStatusPhase `json:"phase,omitempty"`

		// Version Version is the effective version bundle that is currently applied to this
		// Instance. On the first reconciliation the provider-runtime writes the
		// resolved default bundle name here and uses this value on every subsequent
		// reconciliation when spec.version is empty. This ensures that a Provider
		// upgrade (which may change the default bundle) never silently triggers an
		// unintended database upgrade on existing Instances.
		//
		// GitOps tools (ArgoCD, Flux) exclude status from diff calculations by
		// default, so this field does not cause spurious out-of-sync alerts.
		Version *string `json:"version,omitempty"`
	} `json:"status,omitempty"`
}

// InstanceSpecComponentsResourcesLimits0 defines model for .
type InstanceSpecComponentsResourcesLimits0 = int

// InstanceSpecComponentsResourcesLimits1 defines model for .
type InstanceSpecComponentsResourcesLimits1 = string

// Instance_Spec_Components_Resources_Limits_AdditionalProperties defines model for Instance.Spec.Components.Resources.Limits.AdditionalProperties.
type Instance_Spec_Components_Resources_Limits_AdditionalProperties struct {
	union json.RawMessage
}

// InstanceSpecComponentsResourcesRequests0 defines model for .
type InstanceSpecComponentsResourcesRequests0 = int

// InstanceSpecComponentsResourcesRequests1 defines model for .
type InstanceSpecComponentsResourcesRequests1 = string

// Instance_Spec_Components_Resources_Requests_AdditionalProperties defines model for Instance.Spec.Components.Resources.Requests.AdditionalProperties.
type Instance_Spec_Components_Resources_Requests_AdditionalProperties struct {
	union json.RawMessage
}

// InstanceSpecComponentsStorageSize0 defines model for .
type InstanceSpecComponentsStorageSize0 = int

// InstanceSpecComponentsStorageSize1 defines model for .
type InstanceSpecComponentsStorageSize1 = string

// Instance_Spec_Components_Storage_Size defines model for Instance.Spec.Components.Storage.Size.
type Instance_Spec_Components_Storage_Size struct {
	union json.RawMessage
}

// InstanceStatusConditionsStatus status of the condition, one of True, False, Unknown.
type InstanceStatusConditionsStatus string

// InstanceStatusPhase Phase of the database cluster.
type InstanceStatusPhase string

// InstanceConnectionDetails ConnectionDetails holds the typed connection details for a database instance. These are written by the provider-runtime reconciler to a Kubernetes Secret and later read back by the API server to serve the connection endpoint. They follow the Service Binding well-known keys where applicable.
type InstanceConnectionDetails struct {
	// Host Host is the hostname or IP address to connect to
	Host *string `json:"host,omitempty"`

	// Password Password is the password for authentication
	Password *string `json:"password,omitempty"`

	// Port Port is the port number to connect to
	Port *string `json:"port,omitempty"`

	// Provider Provider is the provider that manages this instance
	Provider *string `json:"provider,omitempty"`

	// Type Type is the type of database (e.g., mongodb, postgresql, mysql)
	Type *string `json:"type,omitempty"`

	// Uri URI is a pre-built connection URI
	Uri *string `json:"uri,omitempty"`

	// Username Username is the username for authentication
	Username             *string           `json:"username,omitempty"`
	AdditionalProperties map[string]string `json:"-"`
}

// InstanceList InstanceList is an object that contains the list of the existing instances.
type InstanceList struct {
	// ApiVersion APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
	ApiVersion *string     `json:"apiVersion,omitempty"`
	Items      *[]Instance `json:"items,omitempty"`

	// Kind Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
	Kind     *string `json:"kind,omitempty"`
	Metadata *struct {
		// Name Name must be unique within a namespace. Is required when creating resources, although some resources may allow a client to request the generation of an appropriate name automatically. Name is primarily intended for creation idempotence and configuration definition. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names#names
		Name *string `json:"name,omitempty"`

		// Namespace Namespace defines the space within which each name must be unique. An empty namespace is equivalent to the "default" namespace, but "default" is the canonical representation. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/namespaces
		Namespace *string `json:"namespace,omitempty"`
	} `json:"metadata,omitempty"`
}

// MonitoringConfig MonitoringConfig is the Schema for the monitoringconfigs API.
type MonitoringConfig struct {
	// ApiVersion APIVersion defines the versioned schema of this representation of an object.
	// Servers should convert recognized schemas to the latest internal value, and
	// may reject unrecognized values.
	// More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
	ApiVersion *string `json:"apiVersion,omitempty"`

	// Kind Kind is a string value representing the REST resource this object represents.
	// Servers may infer this from the endpoint the client submits requests to.
	// Cannot be updated.
	// In CamelCase.
	// More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
	Kind     *string                 `json:"kind,omitempty"`
	Metadata *map[string]interface{} `json:"metadata,omitempty"`

	// Spec spec defines the desired state of MonitoringConfig
	Spec struct {
		// CredentialsSecretName CredentialsSecretName is the reference to the secret containing the API key.
		// It contains `apiKey` key with the API key value.
		CredentialsSecretName string `json:"credentialsSecretName"`

		// Type Type is the name of monitoring tool (e.g., "pmm").
		Type MonitoringConfigSpecType `json:"type"`

		// Url URL is the URL of the monitoring server (e.g., PMM server URL).
		Url string `json:"url"`

		// VerifyTLS VerifyTLS is set to ensure TLS/SSL verification.
		// If unspecified, the default value is true.
		VerifyTLS *bool `json:"verifyTLS,omitempty"`
	} `json:"spec"`

	// Status status defines the observed state of MonitoringConfig
	Status *struct {
		// InUse InUse is a flag that indicates if any Instance uses the monitoring config.
		InUse *bool `json:"inUse,omitempty"`

		// LastObservedGeneration LastObservedGeneration is the most recent generation observed for this MonitoringConfig.
		LastObservedGeneration *int64 `json:"lastObservedGeneration,omitempty"`

		// PmmServerVersion PMMServerVersion shows PMM server version.
		PmmServerVersion *string `json:"pmmServerVersion,omitempty"`
	} `json:"status,omitempty"`
}

// MonitoringConfigSpecType Type is the name of monitoring tool (e.g., "pmm").
type MonitoringConfigSpecType string

// MonitoringConfigList MonitoringConfigList is an object that contains the list of the existing monitoringconfigs.
type MonitoringConfigList struct {
	// ApiVersion APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
	ApiVersion *string             `json:"apiVersion,omitempty"`
	Items      *[]MonitoringConfig `json:"items,omitempty"`

	// Kind Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
	Kind     *string `json:"kind,omitempty"`
	Metadata *struct {
		// Name Name must be unique within a namespace. Is required when creating resources, although some resources may allow a client to request the generation of an appropriate name automatically. Name is primarily intended for creation idempotence and configuration definition. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names#names
		Name *string `json:"name,omitempty"`

		// Namespace Namespace defines the space within which each name must be unique. An empty namespace is equivalent to the "default" namespace, but "default" is the canonical representation. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/namespaces
		Namespace *string `json:"namespace,omitempty"`
	} `json:"metadata,omitempty"`
}

// Provider Provider is the Schema for the providers API
type Provider struct {
	// ApiVersion APIVersion defines the versioned schema of this representation of an object.
	// Servers should convert recognized schemas to the latest internal value, and
	// may reject unrecognized values.
	// More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
	ApiVersion *string `json:"apiVersion,omitempty"`

	// Kind Kind is a string value representing the REST resource this object represents.
	// Servers may infer this from the endpoint the client submits requests to.
	// Cannot be updated.
	// In CamelCase.
	// More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
	Kind     *string                 `json:"kind,omitempty"`
	Metadata *map[string]interface{} `json:"metadata,omitempty"`

	// Spec ProviderSpec defines the desired state of Provider
	Spec struct {
		ComponentTypes *map[string]struct {
			Versions *[]struct {
				Default *bool   `json:"default,omitempty"`
				Image   *string `json:"image,omitempty"`
				Version *string `json:"version,omitempty"`
			} `json:"versions,omitempty"`
		} `json:"componentTypes,omitempty"`
		Components *map[string]struct {
			// CustomSpecSchema CustomSpecSchema holds the OpenAPI v3 schema for this component's CustomSpec.
			CustomSpecSchema *map[string]interface{} `json:"customSpecSchema,omitempty"`
			Type             *string                 `json:"type,omitempty"`
		} `json:"components,omitempty"`

		// GlobalConfigSchema GlobalConfigSchema holds the OpenAPI v3 schema for the global configuration.
		GlobalConfigSchema *map[string]interface{} `json:"globalConfigSchema,omitempty"`
		Topologies         *map[string]struct {
			Components *map[string]struct {
				Optional *bool `json:"optional,omitempty"`
			} `json:"components,omitempty"`

			// ConfigSchema ConfigSchema holds the OpenAPI v3 schema for topology-specific configuration.
			ConfigSchema *map[string]interface{} `json:"configSchema,omitempty"`
		} `json:"topologies,omitempty"`

		// UiSchema UISchema holds the UI rendering hints for each topology.
		UiSchema *map[string]interface{} `json:"uiSchema,omitempty"`

		// Versions Versions defines curated version bundles — named sets of component
		// versions that are known to be mutually compatible. Users reference
		// a bundle via Instance.Spec.Version. If the user does not set a version,
		// the bundle whose Default field is true is used automatically.
		Versions *[]struct {
			// Components Components maps component names to their version strings for this bundle.
			// Keys must match component names defined in ProviderSpec.Components.
			Components *map[string]string `json:"components,omitempty"`

			// Default Default marks this bundle as the implicit choice when an Instance omits
			// Spec.Version entirely. Exactly one bundle should have Default: true.
			Default *bool `json:"default,omitempty"`

			// Name Name is the unique identifier for this bundle (e.g. "8.0.12").
			// Users set Instance.Spec.Version to this value to select the bundle.
			Name string `json:"name"`
		} `json:"versions,omitempty"`
	} `json:"spec"`

	// Status ProviderStatus defines the observed state of Provider.
	Status *struct {
		Conditions *[]struct {
			// LastTransitionTime lastTransitionTime is the last time the condition transitioned from one status to another.
			// This should be when the underlying condition changed.  If that is not known, then using the time when the API field changed is acceptable.
			LastTransitionTime time.Time `json:"lastTransitionTime"`

			// Message message is a human readable message indicating details about the transition.
			// This may be an empty string.
			Message string `json:"message"`

			// ObservedGeneration observedGeneration represents the .metadata.generation that the condition was set based upon.
			// For instance, if .metadata.generation is currently 12, but the .status.conditions[x].observedGeneration is 9, the condition is out of date
			// with respect to the current state of the instance.
			ObservedGeneration *int64 `json:"observedGeneration,omitempty"`

			// Reason reason contains a programmatic identifier indicating the reason for the condition's last transition.
			// Producers of specific condition types may define expected values and meanings for this field,
			// and whether the values are considered a guaranteed API.
			// The value should be a CamelCase string.
			// This field may not be empty.
			Reason string `json:"reason"`

			// Status status of the condition, one of True, False, Unknown.
			Status ProviderStatusConditionsStatus `json:"status"`

			// Type type of condition in CamelCase or in foo.example.com/CamelCase.
			Type string `json:"type"`
		} `json:"conditions,omitempty"`
	} `json:"status,omitempty"`
}

// ProviderStatusConditionsStatus status of the condition, one of True, False, Unknown.
type ProviderStatusConditionsStatus string

// ProviderList ProviderList is an object that contains the list of the existing providers.
type ProviderList struct {
	// ApiVersion APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
	ApiVersion *string     `json:"apiVersion,omitempty"`
	Items      *[]Provider `json:"items,omitempty"`

	// Kind Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
	Kind     *string `json:"kind,omitempty"`
	Metadata *struct {
		// Name Name must be unique within a namespace. Is required when creating resources, although some resources may allow a client to request the generation of an appropriate name automatically. Name is primarily intended for creation idempotence and configuration definition. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names#names
		Name *string `json:"name,omitempty"`
	} `json:"metadata,omitempty"`
}

// Restore Restore is the Schema for the restores API.
type Restore struct {
	// ApiVersion APIVersion defines the versioned schema of this representation of an object.
	// Servers should convert recognized schemas to the latest internal value, and
	// may reject unrecognized values.
	// More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
	ApiVersion *string `json:"apiVersion,omitempty"`

	// Kind Kind is a string value representing the REST resource this object represents.
	// Servers may infer this from the endpoint the client submits requests to.
	// Cannot be updated.
	// In CamelCase.
	// More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
	Kind     *string                 `json:"kind,omitempty"`
	Metadata *map[string]interface{} `json:"metadata,omitempty"`

	// Spec RestoreSpec defines the desired state of Restore.
	Spec struct {
		// Config Config is the restore-time configuration validated against the
		// BackupClass's .spec.restoreConfig.openAPIV3Schema.
		Config *map[string]interface{} `json:"config,omitempty"`

		// DataSource DataSource defines where the backup data to restore from is located.
		DataSource struct {
			// BackupName BackupName references an existing Backup CR in the same namespace to
			// restore from. The BackupClass and storage are resolved from the
			// referenced Backup.
			BackupName *string `json:"backupName,omitempty"`

			// External External describes a backup that has no corresponding Backup CR in the
			// cluster (e.g., a backup taken outside of OpenEverest).
			External *struct {
				// BackupClassName BackupClassName is the name of the BackupClass that defines how to
				// restore this external backup.
				BackupClassName string `json:"backupClassName"`

				// Config Config is forwarded to the BackupClass's restore configuration. It is
				// validated against the same schema as Restore.spec.config.
				Config *map[string]interface{} `json:"config,omitempty"`

				// StorageName StorageName references the BackupStorage in the same namespace that
				// describes where the external backup data is located.
				StorageName string `json:"storageName"`
			} `json:"external,omitempty"`

			// Pitr PITR defines point-in-time recovery options. Requires the resolved
			// BackupClass to advertise PITR support via .spec.providerManaged.
			Pitr *struct {
				// Date Date is the target recovery point in time. Required when Type is "date".
				Date *time.Time `json:"date,omitempty"`

				// Type Type is the type of point-in-time recovery: "date" or "latest".
				Type RestoreSpecDataSourcePitrType `json:"type"`
			} `json:"pitr,omitempty"`
		} `json:"dataSource"`

		// InstanceName InstanceName is the name of the Instance to restore into. The Instance
		// must already exist in the same namespace and use a provider listed in
		// the BackupClass's SupportedProviders.
		InstanceName string `json:"instanceName"`
	} `json:"spec"`

	// Status RestoreStatus defines the observed state of Restore.
	Status *struct {
		// CompletedAt CompletedAt is the time when the restore completed successfully.
		CompletedAt *time.Time `json:"completedAt,omitempty"`
		Conditions  *[]struct {
			// LastTransitionTime lastTransitionTime is the last time the condition transitioned from one status to another.
			// This should be when the underlying condition changed.  If that is not known, then using the time when the API field changed is acceptable.
			LastTransitionTime time.Time `json:"lastTransitionTime"`

			// Message message is a human readable message indicating details about the transition.
			// This may be an empty string.
			Message string `json:"message"`

			// ObservedGeneration observedGeneration represents the .metadata.generation that the condition was set based upon.
			// For instance, if .metadata.generation is currently 12, but the .status.conditions[x].observedGeneration is 9, the condition is out of date
			// with respect to the current state of the instance.
			ObservedGeneration *int64 `json:"observedGeneration,omitempty"`

			// Reason reason contains a programmatic identifier indicating the reason for the condition's last transition.
			// Producers of specific condition types may define expected values and meanings for this field,
			// and whether the values are considered a guaranteed API.
			// The value should be a CamelCase string.
			// This field may not be empty.
			Reason string `json:"reason"`

			// Status status of the condition, one of True, False, Unknown.
			Status RestoreStatusConditionsStatus `json:"status"`

			// Type type of condition in CamelCase or in foo.example.com/CamelCase.
			Type string `json:"type"`
		} `json:"conditions,omitempty"`

		// ExecutionMode ExecutionMode is the resolved execution mode at the time the Restore
		// started. Recorded for observability.
		ExecutionMode *RestoreStatusExecutionMode `json:"executionMode,omitempty"`

		// JobName JobName is the reference to the Job that is running the restore.
		// Populated only for Job classes.
		JobName *string `json:"jobName,omitempty"`

		// LastObservedGeneration LastObservedGeneration is the last observed generation of the Restore CR.
		LastObservedGeneration *int64 `json:"lastObservedGeneration,omitempty"`

		// Message Message is a human-readable message about the current state.
		Message *string `json:"message,omitempty"`

		// OperatorRestoreRef OperatorRestoreRef points at the operator-native restore resource the
		// provider created (e.g., PerconaServerMongoDBRestore). Populated only
		// for ProviderManaged classes.
		OperatorRestoreRef *struct {
			// ApiGroup APIGroup is the group for the resource being referenced.
			// If APIGroup is not specified, the specified Kind must be in the core API group.
			// For any other third-party types, APIGroup is required.
			ApiGroup *string `json:"apiGroup,omitempty"`

			// Kind Kind is the type of resource being referenced
			Kind string `json:"kind"`

			// Name Name is the name of resource being referenced
			Name string `json:"name"`
		} `json:"operatorRestoreRef,omitempty"`

		// StartedAt StartedAt is the time when the restore started.
		StartedAt *time.Time `json:"startedAt,omitempty"`

		// State State is the current state of the restore.
		State *string `json:"state,omitempty"`
	} `json:"status,omitempty"`
}

// RestoreSpecDataSourcePitrType Type is the type of point-in-time recovery: "date" or "latest".
type RestoreSpecDataSourcePitrType string

// RestoreStatusConditionsStatus status of the condition, one of True, False, Unknown.
type RestoreStatusConditionsStatus string

// RestoreStatusExecutionMode ExecutionMode is the resolved execution mode at the time the Restore
// started. Recorded for observability.
type RestoreStatusExecutionMode string

// RestoreList RestoreList is an object that contains the list of the existing restores.
type RestoreList struct {
	// ApiVersion APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
	ApiVersion *string    `json:"apiVersion,omitempty"`
	Items      *[]Restore `json:"items,omitempty"`

	// Kind Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
	Kind     *string `json:"kind,omitempty"`
	Metadata *struct {
		// Name Name must be unique within a namespace. Is required when creating resources, although some resources may allow a client to request the generation of an appropriate name automatically. Name is primarily intended for creation idempotence and configuration definition. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names#names
		Name *string `json:"name,omitempty"`

		// Namespace Namespace defines the space within which each name must be unique. An empty namespace is equivalent to the "default" namespace, but "default" is the canonical representation. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/namespaces
		Namespace *string `json:"namespace,omitempty"`
	} `json:"metadata,omitempty"`
}

// Getter for additional properties for InstanceConnectionDetails. Returns the specified
// element and whether it was found
func (a InstanceConnectionDetails) Get(fieldName string) (value string, found bool) {
	if a.AdditionalProperties != nil {
		value, found = a.AdditionalProperties[fieldName]
	}
	return
}

// Setter for additional properties for InstanceConnectionDetails
func (a *InstanceConnectionDetails) Set(fieldName string, value string) {
	if a.AdditionalProperties == nil {
		a.AdditionalProperties = make(map[string]string)
	}
	a.AdditionalProperties[fieldName] = value
}

// Override default JSON handling for InstanceConnectionDetails to handle AdditionalProperties
func (a *InstanceConnectionDetails) UnmarshalJSON(b []byte) error {
	object := make(map[string]json.RawMessage)
	err := json.Unmarshal(b, &object)
	if err != nil {
		return err
	}

	if raw, found := object["host"]; found {
		err = json.Unmarshal(raw, &a.Host)
		if err != nil {
			return fmt.Errorf("error reading 'host': %w", err)
		}
		delete(object, "host")
	}

	if raw, found := object["password"]; found {
		err = json.Unmarshal(raw, &a.Password)
		if err != nil {
			return fmt.Errorf("error reading 'password': %w", err)
		}
		delete(object, "password")
	}

	if raw, found := object["port"]; found {
		err = json.Unmarshal(raw, &a.Port)
		if err != nil {
			return fmt.Errorf("error reading 'port': %w", err)
		}
		delete(object, "port")
	}

	if raw, found := object["provider"]; found {
		err = json.Unmarshal(raw, &a.Provider)
		if err != nil {
			return fmt.Errorf("error reading 'provider': %w", err)
		}
		delete(object, "provider")
	}

	if raw, found := object["type"]; found {
		err = json.Unmarshal(raw, &a.Type)
		if err != nil {
			return fmt.Errorf("error reading 'type': %w", err)
		}
		delete(object, "type")
	}

	if raw, found := object["uri"]; found {
		err = json.Unmarshal(raw, &a.Uri)
		if err != nil {
			return fmt.Errorf("error reading 'uri': %w", err)
		}
		delete(object, "uri")
	}

	if raw, found := object["username"]; found {
		err = json.Unmarshal(raw, &a.Username)
		if err != nil {
			return fmt.Errorf("error reading 'username': %w", err)
		}
		delete(object, "username")
	}

	if len(object) != 0 {
		a.AdditionalProperties = make(map[string]string)
		for fieldName, fieldBuf := range object {
			var fieldVal string
			err := json.Unmarshal(fieldBuf, &fieldVal)
			if err != nil {
				return fmt.Errorf("error unmarshaling field %s: %w", fieldName, err)
			}
			a.AdditionalProperties[fieldName] = fieldVal
		}
	}
	return nil
}

// Override default JSON handling for InstanceConnectionDetails to handle AdditionalProperties
func (a InstanceConnectionDetails) MarshalJSON() ([]byte, error) {
	var err error
	object := make(map[string]json.RawMessage)

	if a.Host != nil {
		object["host"], err = json.Marshal(a.Host)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'host': %w", err)
		}
	}

	if a.Password != nil {
		object["password"], err = json.Marshal(a.Password)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'password': %w", err)
		}
	}

	if a.Port != nil {
		object["port"], err = json.Marshal(a.Port)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'port': %w", err)
		}
	}

	if a.Provider != nil {
		object["provider"], err = json.Marshal(a.Provider)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'provider': %w", err)
		}
	}

	if a.Type != nil {
		object["type"], err = json.Marshal(a.Type)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'type': %w", err)
		}
	}

	if a.Uri != nil {
		object["uri"], err = json.Marshal(a.Uri)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'uri': %w", err)
		}
	}

	if a.Username != nil {
		object["username"], err = json.Marshal(a.Username)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'username': %w", err)
		}
	}

	for fieldName, field := range a.AdditionalProperties {
		object[fieldName], err = json.Marshal(field)
		if err != nil {
			return nil, fmt.Errorf("error marshaling '%s': %w", fieldName, err)
		}
	}
	return json.Marshal(object)
}

// AsInstanceSpecComponentsResourcesLimits0 returns the union data inside the Instance_Spec_Components_Resources_Limits_AdditionalProperties as a InstanceSpecComponentsResourcesLimits0
func (t Instance_Spec_Components_Resources_Limits_AdditionalProperties) AsInstanceSpecComponentsResourcesLimits0() (InstanceSpecComponentsResourcesLimits0, error) {
	var body InstanceSpecComponentsResourcesLimits0
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromInstanceSpecComponentsResourcesLimits0 overwrites any union data inside the Instance_Spec_Components_Resources_Limits_AdditionalProperties as the provided InstanceSpecComponentsResourcesLimits0
func (t *Instance_Spec_Components_Resources_Limits_AdditionalProperties) FromInstanceSpecComponentsResourcesLimits0(v InstanceSpecComponentsResourcesLimits0) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeInstanceSpecComponentsResourcesLimits0 performs a merge with any union data inside the Instance_Spec_Components_Resources_Limits_AdditionalProperties, using the provided InstanceSpecComponentsResourcesLimits0
func (t *Instance_Spec_Components_Resources_Limits_AdditionalProperties) MergeInstanceSpecComponentsResourcesLimits0(v InstanceSpecComponentsResourcesLimits0) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsInstanceSpecComponentsResourcesLimits1 returns the union data inside the Instance_Spec_Components_Resources_Limits_AdditionalProperties as a InstanceSpecComponentsResourcesLimits1
func (t Instance_Spec_Components_Resources_Limits_AdditionalProperties) AsInstanceSpecComponentsResourcesLimits1() (InstanceSpecComponentsResourcesLimits1, error) {
	var body InstanceSpecComponentsResourcesLimits1
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromInstanceSpecComponentsResourcesLimits1 overwrites any union data inside the Instance_Spec_Components_Resources_Limits_AdditionalProperties as the provided InstanceSpecComponentsResourcesLimits1
func (t *Instance_Spec_Components_Resources_Limits_AdditionalProperties) FromInstanceSpecComponentsResourcesLimits1(v InstanceSpecComponentsResourcesLimits1) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeInstanceSpecComponentsResourcesLimits1 performs a merge with any union data inside the Instance_Spec_Components_Resources_Limits_AdditionalProperties, using the provided InstanceSpecComponentsResourcesLimits1
func (t *Instance_Spec_Components_Resources_Limits_AdditionalProperties) MergeInstanceSpecComponentsResourcesLimits1(v InstanceSpecComponentsResourcesLimits1) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

func (t Instance_Spec_Components_Resources_Limits_AdditionalProperties) MarshalJSON() ([]byte, error) {
	b, err := t.union.MarshalJSON()
	return b, err
}

func (t *Instance_Spec_Components_Resources_Limits_AdditionalProperties) UnmarshalJSON(b []byte) error {
	err := t.union.UnmarshalJSON(b)
	return err
}

// AsInstanceSpecComponentsResourcesRequests0 returns the union data inside the Instance_Spec_Components_Resources_Requests_AdditionalProperties as a InstanceSpecComponentsResourcesRequests0
func (t Instance_Spec_Components_Resources_Requests_AdditionalProperties) AsInstanceSpecComponentsResourcesRequests0() (InstanceSpecComponentsResourcesRequests0, error) {
	var body InstanceSpecComponentsResourcesRequests0
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromInstanceSpecComponentsResourcesRequests0 overwrites any union data inside the Instance_Spec_Components_Resources_Requests_AdditionalProperties as the provided InstanceSpecComponentsResourcesRequests0
func (t *Instance_Spec_Components_Resources_Requests_AdditionalProperties) FromInstanceSpecComponentsResourcesRequests0(v InstanceSpecComponentsResourcesRequests0) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeInstanceSpecComponentsResourcesRequests0 performs a merge with any union data inside the Instance_Spec_Components_Resources_Requests_AdditionalProperties, using the provided InstanceSpecComponentsResourcesRequests0
func (t *Instance_Spec_Components_Resources_Requests_AdditionalProperties) MergeInstanceSpecComponentsResourcesRequests0(v InstanceSpecComponentsResourcesRequests0) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsInstanceSpecComponentsResourcesRequests1 returns the union data inside the Instance_Spec_Components_Resources_Requests_AdditionalProperties as a InstanceSpecComponentsResourcesRequests1
func (t Instance_Spec_Components_Resources_Requests_AdditionalProperties) AsInstanceSpecComponentsResourcesRequests1() (InstanceSpecComponentsResourcesRequests1, error) {
	var body InstanceSpecComponentsResourcesRequests1
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromInstanceSpecComponentsResourcesRequests1 overwrites any union data inside the Instance_Spec_Components_Resources_Requests_AdditionalProperties as the provided InstanceSpecComponentsResourcesRequests1
func (t *Instance_Spec_Components_Resources_Requests_AdditionalProperties) FromInstanceSpecComponentsResourcesRequests1(v InstanceSpecComponentsResourcesRequests1) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeInstanceSpecComponentsResourcesRequests1 performs a merge with any union data inside the Instance_Spec_Components_Resources_Requests_AdditionalProperties, using the provided InstanceSpecComponentsResourcesRequests1
func (t *Instance_Spec_Components_Resources_Requests_AdditionalProperties) MergeInstanceSpecComponentsResourcesRequests1(v InstanceSpecComponentsResourcesRequests1) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

func (t Instance_Spec_Components_Resources_Requests_AdditionalProperties) MarshalJSON() ([]byte, error) {
	b, err := t.union.MarshalJSON()
	return b, err
}

func (t *Instance_Spec_Components_Resources_Requests_AdditionalProperties) UnmarshalJSON(b []byte) error {
	err := t.union.UnmarshalJSON(b)
	return err
}

// AsInstanceSpecComponentsStorageSize0 returns the union data inside the Instance_Spec_Components_Storage_Size as a InstanceSpecComponentsStorageSize0
func (t Instance_Spec_Components_Storage_Size) AsInstanceSpecComponentsStorageSize0() (InstanceSpecComponentsStorageSize0, error) {
	var body InstanceSpecComponentsStorageSize0
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromInstanceSpecComponentsStorageSize0 overwrites any union data inside the Instance_Spec_Components_Storage_Size as the provided InstanceSpecComponentsStorageSize0
func (t *Instance_Spec_Components_Storage_Size) FromInstanceSpecComponentsStorageSize0(v InstanceSpecComponentsStorageSize0) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeInstanceSpecComponentsStorageSize0 performs a merge with any union data inside the Instance_Spec_Components_Storage_Size, using the provided InstanceSpecComponentsStorageSize0
func (t *Instance_Spec_Components_Storage_Size) MergeInstanceSpecComponentsStorageSize0(v InstanceSpecComponentsStorageSize0) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsInstanceSpecComponentsStorageSize1 returns the union data inside the Instance_Spec_Components_Storage_Size as a InstanceSpecComponentsStorageSize1
func (t Instance_Spec_Components_Storage_Size) AsInstanceSpecComponentsStorageSize1() (InstanceSpecComponentsStorageSize1, error) {
	var body InstanceSpecComponentsStorageSize1
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromInstanceSpecComponentsStorageSize1 overwrites any union data inside the Instance_Spec_Components_Storage_Size as the provided InstanceSpecComponentsStorageSize1
func (t *Instance_Spec_Components_Storage_Size) FromInstanceSpecComponentsStorageSize1(v InstanceSpecComponentsStorageSize1) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeInstanceSpecComponentsStorageSize1 performs a merge with any union data inside the Instance_Spec_Components_Storage_Size, using the provided InstanceSpecComponentsStorageSize1
func (t *Instance_Spec_Components_Storage_Size) MergeInstanceSpecComponentsStorageSize1(v InstanceSpecComponentsStorageSize1) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

func (t Instance_Spec_Components_Storage_Size) MarshalJSON() ([]byte, error) {
	b, err := t.union.MarshalJSON()
	return b, err
}

func (t *Instance_Spec_Components_Storage_Size) UnmarshalJSON(b []byte) error {
	err := t.union.UnmarshalJSON(b)
	return err
}
