/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export type paths = Record<string, never>;
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @description Backup is the Schema for the backups API. */
        Backup: {
            /**
             * @description APIVersion defines the versioned schema of this representation of an object.
             *     Servers should convert recognized schemas to the latest internal value, and
             *     may reject unrecognized values.
             *     More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
             */
            apiVersion?: string;
            /**
             * @description Kind is a string value representing the REST resource this object represents.
             *     Servers may infer this from the endpoint the client submits requests to.
             *     Cannot be updated.
             *     In CamelCase.
             *     More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
             */
            kind?: string;
            metadata?: Record<string, never>;
            /** @description BackupSpec defines the desired state of Backup. */
            spec: {
                /**
                 * @description BackupClassName is the BackupClass that defines how this Backup is
                 *     executed. The class's executionMode controls the runtime path: Job
                 *     classes are reconciled by the in-cluster Backup job controller;
                 *     ProviderManaged classes are reconciled by the provider's runtime.
                 */
                backupClassName: string;
                /**
                 * @description Config is the backup-time configuration validated against the
                 *     BackupClass's .spec.config.openAPIV3Schema.
                 */
                config?: Record<string, never>;
                /**
                 * @description DeletionPolicy controls what happens to the underlying backup data
                 *     (e.g., the object stored in S3) when this Backup CR is deleted.
                 *     Delete (default) instructs the provider to remove both the
                 *     engine-native backup resource and the data in the configured
                 *     BackupStorage. Retain instructs the provider to remove the
                 *     engine-native backup resource but to leave the underlying data in
                 *     place, so it can be recovered later out-of-band.
                 *
                 *     The field is mutable on a live Backup but is frozen once deletion
                 *     has started: switching policies after .metadata.deletionTimestamp
                 *     has been set is rejected so the cleanup path cannot race with
                 *     itself.
                 * @default Delete
                 */
                deletionPolicy: string & (("Retain" | "Delete") & ("Retain" | "Delete"));
                /**
                 * @description InstanceName is the name of the Instance to back up. The Instance must
                 *     live in the same namespace as this Backup.
                 */
                instanceName: string;
                /**
                 * @description ScheduleName, when set, identifies the InstanceBackupSchedule that
                 *     produced this Backup. Backups created via the API or `kubectl apply`
                 *     leave this field empty (on-demand). The provider's mirroring loop
                 *     sets it when surfacing operator-produced scheduled backups as Backup
                 *     CRs.
                 */
                scheduleName?: string;
                /**
                 * @description StorageName references a BackupStorage in the same namespace that
                 *     defines where the backup data is written. For ProviderManaged classes
                 *     the referenced storage must already be registered on the Instance via
                 *     .spec.backup.storages so the engine can write to it.
                 */
                storageName: string;
            };
            /** @description BackupStatus defines the observed state of Backup. */
            status?: {
                /**
                 * Format: date-time
                 * @description CompletedAt is the time when the backup completed successfully.
                 */
                completedAt?: string;
                conditions?: {
                    /**
                     * Format: date-time
                     * @description lastTransitionTime is the last time the condition transitioned from one status to another.
                     *     This should be when the underlying condition changed.  If that is not known, then using the time when the API field changed is acceptable.
                     */
                    lastTransitionTime: string;
                    /**
                     * @description message is a human readable message indicating details about the transition.
                     *     This may be an empty string.
                     */
                    message: string;
                    /**
                     * Format: int64
                     * @description observedGeneration represents the .metadata.generation that the condition was set based upon.
                     *     For instance, if .metadata.generation is currently 12, but the .status.conditions[x].observedGeneration is 9, the condition is out of date
                     *     with respect to the current state of the instance.
                     */
                    observedGeneration?: number;
                    /**
                     * @description reason contains a programmatic identifier indicating the reason for the condition's last transition.
                     *     Producers of specific condition types may define expected values and meanings for this field,
                     *     and whether the values are considered a guaranteed API.
                     *     The value should be a CamelCase string.
                     *     This field may not be empty.
                     */
                    reason: string;
                    /**
                     * @description status of the condition, one of True, False, Unknown.
                     * @enum {string}
                     */
                    status: "True" | "False" | "Unknown";
                    /** @description type of condition in CamelCase or in foo.example.com/CamelCase. */
                    type: string;
                }[];
                /**
                 * @description ExecutionMode is the resolved execution mode at the time the Backup
                 *     started. Recorded for observability.
                 * @enum {string}
                 */
                executionMode?: "ProviderManaged" | "Job";
                /**
                 * @description JobName is the reference to the Job that is running the backup.
                 *     Populated only for Job classes.
                 */
                jobName?: string;
                /**
                 * Format: int64
                 * @description LastObservedGeneration is the last observed generation of the Backup CR.
                 */
                lastObservedGeneration?: number;
                /** @description Message is a human-readable message about the current state. */
                message?: string;
                /**
                 * @description OperatorBackupRef points at the operator-native backup resource the
                 *     provider created (e.g., PerconaServerMongoDBBackup). Populated only
                 *     for ProviderManaged classes.
                 */
                operatorBackupRef?: {
                    /**
                     * @description APIGroup is the group for the resource being referenced.
                     *     If APIGroup is not specified, the specified Kind must be in the core API group.
                     *     For any other third-party types, APIGroup is required.
                     */
                    apiGroup?: string;
                    /** @description Kind is the type of resource being referenced */
                    kind: string;
                    /** @description Name is the name of resource being referenced */
                    name: string;
                };
                /** @description Size is the size of the backup data as reported by the engine. */
                size?: string;
                /**
                 * Format: date-time
                 * @description StartedAt is the time when the backup started.
                 */
                startedAt?: string;
                /** @description State is the current state of the backup. */
                state?: string;
            };
        };
        /** @description BackupClass is the Schema for the backupclasses API */
        BackupClass: {
            /**
             * @description APIVersion defines the versioned schema of this representation of an object.
             *     Servers should convert recognized schemas to the latest internal value, and
             *     may reject unrecognized values.
             *     More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
             */
            apiVersion?: string;
            /**
             * @description Kind is a string value representing the REST resource this object represents.
             *     Servers may infer this from the endpoint the client submits requests to.
             *     Cannot be updated.
             *     In CamelCase.
             *     More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
             */
            kind?: string;
            metadata?: Record<string, never>;
            /** @description BackupClassSpec defines the desired state of BackupClass. */
            spec: {
                /**
                 * @description Config contains the OpenAPI v3 schema describing the backup-time
                 *     configuration accepted by this class. Backup.spec.config is validated
                 *     against this schema.
                 */
                config?: {
                    /** @description OpenAPIV3Schema is the OpenAPI v3 schema of the backup class. */
                    openAPIV3Schema?: unknown;
                };
                /** @description Description is the description of the backup class. */
                description?: string;
                /** @description DisplayName is a human-readable name for the backup class. */
                displayName?: string;
                /**
                 * @description ExecutionMode selects between job-based and provider-managed execution.
                 * @enum {string}
                 */
                executionMode: "ProviderManaged" | "Job";
                /**
                 * @description InstanceConstraints defines compatibility requirements that must be
                 *     satisfied by an Instance before this backup class can be used with it.
                 */
                instanceConstraints?: {
                    /**
                     * @description RequiredFields contains a list of fields that must be set in the Instance spec.
                     *     Each key is a JSON path expressions that points to a field in the Instance spec.
                     *     For example, ".spec.engine.type" or ".spec.dataSource.dataImport.config.someField".
                     */
                    requiredFields?: string[];
                };
                /**
                 * @description Job contains execution detail for ExecutionMode="Job". Must be unset
                 *     when ExecutionMode is "ProviderManaged".
                 */
                job?: {
                    /**
                     * @description CleanupJobSpec is the optional specification of a cleanup job that runs
                     *     when the parent Backup or Restore CR is deleted.
                     */
                    cleanupJobSpec?: {
                        /** @description Command is the command to run the backup class. */
                        command?: string[];
                        /** @description Image is the image of the backup class. */
                        image?: string;
                    };
                    /**
                     * @description ClusterPermissions are cluster-scoped PolicyRules granted via a
                     *     generated ClusterRole and ClusterRoleBinding.
                     */
                    clusterPermissions?: {
                        /**
                         * @description APIGroups is the name of the APIGroup that contains the resources.  If multiple API groups are specified, any action requested against one of
                         *     the enumerated resources in any API group will be allowed. "" represents the core API group and "*" represents all API groups.
                         */
                        apiGroups?: string[];
                        /**
                         * @description NonResourceURLs is a set of partial urls that a user should have access to.  *s are allowed, but only as the full, final step in the path
                         *     Since non-resource URLs are not namespaced, this field is only applicable for ClusterRoles referenced from a ClusterRoleBinding.
                         *     Rules can either apply to API resources (such as "pods" or "secrets") or non-resource URL paths (such as "/api"),  but not both.
                         */
                        nonResourceURLs?: string[];
                        /** @description ResourceNames is an optional white list of names that the rule applies to.  An empty set means that everything is allowed. */
                        resourceNames?: string[];
                        /** @description Resources is a list of resources this rule applies to. '*' represents all resources. */
                        resources?: string[];
                        /** @description Verbs is a list of Verbs that apply to ALL the ResourceKinds contained in this rule. '*' represents all verbs. */
                        verbs: string[];
                    }[];
                    /** @description JobSpec is the specification of the backup or restore job. */
                    jobSpec: {
                        /** @description Command is the command to run the backup class. */
                        command?: string[];
                        /** @description Image is the image of the backup class. */
                        image?: string;
                    };
                    /**
                     * @description Permissions are namespace-scoped PolicyRules granted to the job pod via
                     *     a generated Role and RoleBinding.
                     */
                    permissions?: {
                        /**
                         * @description APIGroups is the name of the APIGroup that contains the resources.  If multiple API groups are specified, any action requested against one of
                         *     the enumerated resources in any API group will be allowed. "" represents the core API group and "*" represents all API groups.
                         */
                        apiGroups?: string[];
                        /**
                         * @description NonResourceURLs is a set of partial urls that a user should have access to.  *s are allowed, but only as the full, final step in the path
                         *     Since non-resource URLs are not namespaced, this field is only applicable for ClusterRoles referenced from a ClusterRoleBinding.
                         *     Rules can either apply to API resources (such as "pods" or "secrets") or non-resource URL paths (such as "/api"),  but not both.
                         */
                        nonResourceURLs?: string[];
                        /** @description ResourceNames is an optional white list of names that the rule applies to.  An empty set means that everything is allowed. */
                        resourceNames?: string[];
                        /** @description Resources is a list of resources this rule applies to. '*' represents all resources. */
                        resources?: string[];
                        /** @description Verbs is a list of Verbs that apply to ALL the ResourceKinds contained in this rule. '*' represents all verbs. */
                        verbs: string[];
                    }[];
                };
                /**
                 * @description ProviderManaged contains hints for ExecutionMode="ProviderManaged". The
                 *     schema is intentionally open: providers may surface capability
                 *     information (e.g., whether PITR is supported, schedule expression
                 *     dialect) without forcing a CRD change. Must be unset when
                 *     ExecutionMode is "Job".
                 */
                providerManaged?: {
                    /**
                     * @description Limits caps how many storages, PITR-enabled storages, and schedules per
                     *     storage an Instance may declare under .spec.backup when this class is
                     *     selected. Unset fields mean "unlimited" (still subject to the core
                     *     MaxItems ceilings on InstanceBackupSpec). The runtime enforces these
                     *     caps both at admission time (provider validation webhook) and before
                     *     dispatching ConfigureBackup; providers may add engine-specific
                     *     constraints on top via Context.BackupClassLimits().
                     */
                    limits?: {
                        /**
                         * Format: int32
                         * @description MaxPITREnabledStorages is the maximum number of storages on an Instance
                         *     that may set .pitr.enabled=true at the same time. Engines that support
                         *     a single PITR stream (e.g. PSMDB, PXC) declare 1 here. Engines that
                         *     archive WAL to every repo (e.g. PG) leave this unset.
                         */
                        maxPITREnabledStorages?: number;
                        /**
                         * Format: int32
                         * @description MaxSchedulesPerStorage is the maximum number of recurring schedules
                         *     allowed per Instance storage entry.
                         */
                        maxSchedulesPerStorage?: number;
                        /**
                         * Format: int32
                         * @description MaxStorages is the maximum number of entries allowed in
                         *     Instance.spec.backup.storages.
                         */
                        maxStorages?: number;
                    };
                    /**
                     * @description PITRConfigSchema describes the shape of per-storage PITR custom config
                     *     (InstanceBackupStoragePITR.Config). The field is free-form and opaque
                     *     to the runtime; the provider validates Instance.spec.backup PITR
                     *     payloads against it inside Validate(). The recommended payload is an
                     *     OpenAPI v3 schema fragment so the UI can render a matching form, but
                     *     any provider-specific dialect is permitted.
                     */
                    pitrConfigSchema?: Record<string, never>;
                    /**
                     * @description SupportsPITR indicates whether this class supports point-in-time recovery.
                     *     Used by Restore validation when Restore.spec.dataSource.pitr is set.
                     */
                    supportsPITR?: boolean;
                };
                /**
                 * @description RestoreConfig contains the OpenAPI v3 schema describing the restore-time
                 *     configuration accepted by this class. Restore.spec.config is validated
                 *     against this schema.
                 */
                restoreConfig?: {
                    /** @description OpenAPIV3Schema is the OpenAPI v3 schema of the backup class. */
                    openAPIV3Schema?: unknown;
                };
                /**
                 * @description RestoreJob contains execution detail for the restore job in
                 *     ExecutionMode="Job". Must be unset when ExecutionMode is
                 *     "ProviderManaged".
                 */
                restoreJob?: {
                    /**
                     * @description CleanupJobSpec is the optional specification of a cleanup job that runs
                     *     when the parent Backup or Restore CR is deleted.
                     */
                    cleanupJobSpec?: {
                        /** @description Command is the command to run the backup class. */
                        command?: string[];
                        /** @description Image is the image of the backup class. */
                        image?: string;
                    };
                    /**
                     * @description ClusterPermissions are cluster-scoped PolicyRules granted via a
                     *     generated ClusterRole and ClusterRoleBinding.
                     */
                    clusterPermissions?: {
                        /**
                         * @description APIGroups is the name of the APIGroup that contains the resources.  If multiple API groups are specified, any action requested against one of
                         *     the enumerated resources in any API group will be allowed. "" represents the core API group and "*" represents all API groups.
                         */
                        apiGroups?: string[];
                        /**
                         * @description NonResourceURLs is a set of partial urls that a user should have access to.  *s are allowed, but only as the full, final step in the path
                         *     Since non-resource URLs are not namespaced, this field is only applicable for ClusterRoles referenced from a ClusterRoleBinding.
                         *     Rules can either apply to API resources (such as "pods" or "secrets") or non-resource URL paths (such as "/api"),  but not both.
                         */
                        nonResourceURLs?: string[];
                        /** @description ResourceNames is an optional white list of names that the rule applies to.  An empty set means that everything is allowed. */
                        resourceNames?: string[];
                        /** @description Resources is a list of resources this rule applies to. '*' represents all resources. */
                        resources?: string[];
                        /** @description Verbs is a list of Verbs that apply to ALL the ResourceKinds contained in this rule. '*' represents all verbs. */
                        verbs: string[];
                    }[];
                    /** @description JobSpec is the specification of the backup or restore job. */
                    jobSpec: {
                        /** @description Command is the command to run the backup class. */
                        command?: string[];
                        /** @description Image is the image of the backup class. */
                        image?: string;
                    };
                    /**
                     * @description Permissions are namespace-scoped PolicyRules granted to the job pod via
                     *     a generated Role and RoleBinding.
                     */
                    permissions?: {
                        /**
                         * @description APIGroups is the name of the APIGroup that contains the resources.  If multiple API groups are specified, any action requested against one of
                         *     the enumerated resources in any API group will be allowed. "" represents the core API group and "*" represents all API groups.
                         */
                        apiGroups?: string[];
                        /**
                         * @description NonResourceURLs is a set of partial urls that a user should have access to.  *s are allowed, but only as the full, final step in the path
                         *     Since non-resource URLs are not namespaced, this field is only applicable for ClusterRoles referenced from a ClusterRoleBinding.
                         *     Rules can either apply to API resources (such as "pods" or "secrets") or non-resource URL paths (such as "/api"),  but not both.
                         */
                        nonResourceURLs?: string[];
                        /** @description ResourceNames is an optional white list of names that the rule applies to.  An empty set means that everything is allowed. */
                        resourceNames?: string[];
                        /** @description Resources is a list of resources this rule applies to. '*' represents all resources. */
                        resources?: string[];
                        /** @description Verbs is a list of Verbs that apply to ALL the ResourceKinds contained in this rule. '*' represents all verbs. */
                        verbs: string[];
                    }[];
                };
                /**
                 * @description SupportedProviders is the list of provider names that this backup class
                 *     supports. The Instance.spec.provider must appear in this list for the
                 *     class to be usable on that Instance.
                 */
                supportedProviders?: string[];
                /**
                 * @description UISchema contains free-form rendering hints for the frontend forms that
                 *     configure backup, restore, and PITR for an Instance using this class.
                 *     The runtime treats this field as opaque; only the UI consumes it. The
                 *     recommended shape groups fields by the modal that renders them
                 *     (e.g. "backup", "pitr", "restore"), mirroring Provider.spec.uiSchema.
                 */
                uiSchema?: Record<string, never>;
            };
            /** @description BackupClassStatus defines the observed state of BackupClass. */
            status?: {
                conditions?: {
                    /**
                     * Format: date-time
                     * @description lastTransitionTime is the last time the condition transitioned from one status to another.
                     *     This should be when the underlying condition changed.  If that is not known, then using the time when the API field changed is acceptable.
                     */
                    lastTransitionTime: string;
                    /**
                     * @description message is a human readable message indicating details about the transition.
                     *     This may be an empty string.
                     */
                    message: string;
                    /**
                     * Format: int64
                     * @description observedGeneration represents the .metadata.generation that the condition was set based upon.
                     *     For instance, if .metadata.generation is currently 12, but the .status.conditions[x].observedGeneration is 9, the condition is out of date
                     *     with respect to the current state of the instance.
                     */
                    observedGeneration?: number;
                    /**
                     * @description reason contains a programmatic identifier indicating the reason for the condition's last transition.
                     *     Producers of specific condition types may define expected values and meanings for this field,
                     *     and whether the values are considered a guaranteed API.
                     *     The value should be a CamelCase string.
                     *     This field may not be empty.
                     */
                    reason: string;
                    /**
                     * @description status of the condition, one of True, False, Unknown.
                     * @enum {string}
                     */
                    status: "True" | "False" | "Unknown";
                    /** @description type of condition in CamelCase or in foo.example.com/CamelCase. */
                    type: string;
                }[];
            };
        };
        /** @description BackupClassList is an object that contains the list of the existing backupclasss. */
        BackupClassList: {
            /** @description APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources */
            apiVersion?: string;
            items?: components["schemas"]["BackupClass"][];
            /** @description Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds */
            kind?: string;
            metadata?: {
                /** @description Name must be unique within a namespace. Is required when creating resources, although some resources may allow a client to request the generation of an appropriate name automatically. Name is primarily intended for creation idempotence and configuration definition. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names#names */
                name?: string;
            };
        };
        /** @description BackupList is an object that contains the list of the existing backups. */
        BackupList: {
            /** @description APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources */
            apiVersion?: string;
            items?: components["schemas"]["Backup"][];
            /** @description Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds */
            kind?: string;
            metadata?: {
                /** @description Name must be unique within a namespace. Is required when creating resources, although some resources may allow a client to request the generation of an appropriate name automatically. Name is primarily intended for creation idempotence and configuration definition. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names#names */
                name?: string;
                /** @description Namespace defines the space within which each name must be unique. An empty namespace is equivalent to the "default" namespace, but "default" is the canonical representation. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/namespaces */
                namespace?: string;
            };
        };
        /** @description BackupStorage is the Schema for the backupstorages API. */
        BackupStorage: {
            /**
             * @description APIVersion defines the versioned schema of this representation of an object.
             *     Servers should convert recognized schemas to the latest internal value, and
             *     may reject unrecognized values.
             *     More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
             */
            apiVersion?: string;
            /**
             * @description Kind is a string value representing the REST resource this object represents.
             *     Servers may infer this from the endpoint the client submits requests to.
             *     Cannot be updated.
             *     In CamelCase.
             *     More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
             */
            kind?: string;
            metadata?: Record<string, never>;
            /**
             * @description BackupStorageSpec defines the desired state of a BackupStorage.
             *
             *     A BackupStorage is a reusable, namespaced reference to an object store
             *     (today only S3-compatible) plus the credentials needed to talk to it.
             *     It is referenced by name from:
             *
             *       - Instance.spec.backup.storages[].storageRef
             *       - Backup.spec.storageName
             *       - Restore.spec.dataSource.external.storageName
             *
             *     Decoupling storage from individual Backup CRs makes provider-managed
             *     backups (e.g. PBM, pgBackRest) practical: the provider can register a
             *     fixed set of storages on the engine without recomputing them from a
             *     dynamic list of Backup CRs.
             */
            spec: {
                /**
                 * @description S3 contains S3-compatible storage configuration.
                 *     Required when Type is "s3".
                 */
                s3?: {
                    /**
                     * @description AccessKeyID is a write-only convenience input. When set, a webhook
                     *     stores it in the Secret named by CredentialsSecretName and clears
                     *     this field. It is never persisted on the BackupStorage object.
                     */
                    accessKeyId?: string;
                    /** @description Bucket is the name of the S3 bucket. */
                    bucket: string;
                    /**
                     * @description CredentialsSecretName is the name of the Secret in the same namespace
                     *     that holds the AWS_ACCESS_KEY_ID and AWS_SECRET_ACCESS_KEY keys.
                     */
                    credentialsSecretName: string;
                    /** @description EndpointURL is the endpoint URL of the S3-compatible service. */
                    endpointURL: string;
                    /**
                     * @description ForcePathStyle forces path-style URLs (bucket name in the path
                     *     instead of the host). Defaults to false.
                     * @default false
                     */
                    forcePathStyle: boolean;
                    /** @description Region is the region of the S3 bucket. */
                    region: string;
                    /** @description SecretAccessKey is a write-only convenience input. See AccessKeyID. */
                    secretAccessKey?: string;
                    /**
                     * @description VerifyTLS enables TLS certificate verification.
                     *     Defaults to true.
                     * @default true
                     */
                    verifyTLS: boolean;
                };
                /**
                 * @description Type is the object storage type. Today only "s3" is supported.
                 * @enum {string}
                 */
                type: "s3";
            };
            /** @description BackupStorageStatus defines the observed state of a BackupStorage. */
            status?: Record<string, never>;
        };
        /** @description BackupStorageList is an object that contains the list of the existing backupstorages. */
        BackupStorageList: {
            /** @description APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources */
            apiVersion?: string;
            items?: components["schemas"]["BackupStorage"][];
            /** @description Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds */
            kind?: string;
            metadata?: {
                /** @description Name must be unique within a namespace. Is required when creating resources, although some resources may allow a client to request the generation of an appropriate name automatically. Name is primarily intended for creation idempotence and configuration definition. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names#names */
                name?: string;
                /** @description Namespace defines the space within which each name must be unique. An empty namespace is equivalent to the "default" namespace, but "default" is the canonical representation. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/namespaces */
                namespace?: string;
            };
        };
        /** @description Instance is the Schema for the instances API */
        Instance: {
            /**
             * @description APIVersion defines the versioned schema of this representation of an object.
             *     Servers should convert recognized schemas to the latest internal value, and
             *     may reject unrecognized values.
             *     More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
             */
            apiVersion?: string;
            /**
             * @description Kind is a string value representing the REST resource this object represents.
             *     Servers may infer this from the endpoint the client submits requests to.
             *     Cannot be updated.
             *     In CamelCase.
             *     More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
             */
            kind?: string;
            metadata?: Record<string, never>;
            /** @description InstanceSpec defines the desired state of Instance */
            spec: {
                /**
                 * @description Backup configures the backup feature for this Instance. When enabled,
                 *     the provider's reconciler is given the resolved BackupClass and storage
                 *     list so it can configure the engine accordingly (sidecars, agent
                 *     configuration, etc.). Required for ProviderManaged BackupClasses; Job
                 *     classes do not need an entry here because they read directly from
                 *     individual Backup CRs.
                 */
                backup?: {
                    /**
                     * @description ClassRef references the BackupClass that the provider should use to
                     *     configure the engine. The class must have ExecutionMode=ProviderManaged
                     *     and list the Instance's provider in its SupportedProviders.
                     */
                    classRef: {
                        /** @description Name is the BackupClass name. BackupClasses are cluster-scoped. */
                        name: string;
                    };
                    /**
                     * @description Enabled toggles the backup feature for this Instance. When false the
                     *     runtime skips ConfigureBackup() and the rest of this struct is ignored.
                     */
                    enabled: boolean;
                    /**
                     * @description Storages registers BackupStorages on the engine. Each entry maps a
                     *     logical name (visible to the engine and reused by Backup CRs via
                     *     .spec.storageName) to a BackupStorage resource. Schedules and PITR are
                     *     configured per storage via the nested .schedules and .pitr fields.
                     */
                    storages?: {
                        /**
                         * @description Main marks this storage as the engine's default. At most one storage
                         *     per Instance may be marked main.
                         */
                        main?: boolean;
                        /**
                         * @description Name is the logical name the engine uses for this storage. It is also
                         *     the value that Backup CRs target via .spec.storageName.
                         */
                        name: string;
                        /**
                         * @description PITR enables and configures point-in-time recovery writing to this
                         *     storage. Requires the BackupClass to advertise PITR support via
                         *     .spec.providerManaged. Engines that support only a single PITR stream
                         *     (e.g. PSMDB, PXC) require at most one storage on the Instance to set
                         *     .pitr.enabled=true; this is enforced by the provider, not by the
                         *     core schema (PG legitimately archives WAL to every configured repo).
                         */
                        pitr?: {
                            /**
                             * @description Config holds provider-specific PITR options. The schema is defined by
                             *     the BackupClass via .spec.providerManaged.
                             */
                            config?: Record<string, never>;
                            /** @description Enabled toggles PITR for this storage. */
                            enabled: boolean;
                        };
                        /**
                         * @description Schedules registers recurring backup tasks that write to this storage.
                         *     Schedules produce Backup CRs (via the provider's mirroring loop) using
                         *     the operator-native scheduler — the runtime never spawns CronJobs for
                         *     ProviderManaged BackupClasses. Schedule names must be unique across
                         *     all storages on the Instance.
                         */
                        schedules?: {
                            /**
                             * @description Cron is a standard 5-field cron expression. The provider may reject
                             *     expressions the engine does not support.
                             */
                            cron: string;
                            /**
                             * @description Enabled toggles the schedule. A disabled schedule is removed from
                             *     the engine without losing its definition on the Instance.
                             */
                            enabled: boolean;
                            /**
                             * @description Name uniquely identifies the schedule. The provider uses it as the
                             *     schedule key on the engine and as the value of Backup.spec.scheduleName
                             *     on mirrored Backup CRs. Names must be unique across all storages on
                             *     the Instance.
                             */
                            name: string;
                            /**
                             * Format: int32
                             * @description RetentionCopies is the number of recent backups to keep for this
                             *     schedule. Zero (or unset) means "keep all". Negative values are
                             *     rejected.
                             */
                            retentionCopies?: number;
                        }[];
                        /** @description StorageRef references a BackupStorage in the same namespace. */
                        storageRef: {
                            /**
                             * @description Name of the referent.
                             *     This field is effectively required, but due to backwards compatibility is
                             *     allowed to be empty. Instances of this type with an empty value here are
                             *     almost certainly wrong.
                             *     More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names
                             * @default
                             */
                            name: string;
                        };
                    }[];
                };
                /**
                 * @description Components defines the component instances for this cluster.
                 *     The keys are component names (e.g., "engine", "proxy", "backupAgent").
                 *     Which components are valid depends on the selected topology.
                 */
                components?: {
                    [key: string]: {
                        /** @description Config specifies the component specific configuration. */
                        config?: {
                            /**
                             * @description LocalObjectReference contains enough information to let you locate the
                             *     referenced object inside the same namespace.
                             */
                            configMapRef?: {
                                /**
                                 * @description Name of the referent.
                                 *     This field is effectively required, but due to backwards compatibility is
                                 *     allowed to be empty. Instances of this type with an empty value here are
                                 *     almost certainly wrong.
                                 *     More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names
                                 * @default
                                 */
                                name: string;
                            };
                            key?: string;
                            /**
                             * @description LocalObjectReference contains enough information to let you locate the
                             *     referenced object inside the same namespace.
                             */
                            secretRef?: {
                                /**
                                 * @description Name of the referent.
                                 *     This field is effectively required, but due to backwards compatibility is
                                 *     allowed to be empty. Instances of this type with an empty value here are
                                 *     almost certainly wrong.
                                 *     More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names
                                 * @default
                                 */
                                name: string;
                            };
                        };
                        /**
                         * @description CustomSpec provides an API for customising this component.
                         *     The API schema is defined by the provider's ComponentSchemas.
                         */
                        customSpec?: Record<string, never>;
                        /**
                         * @description Image specifies an override for the image to use.
                         *     When unspecified, it is autmatically set from the ComponentVersions
                         *     based on the Version specified.
                         */
                        image?: string;
                        /** @description Name of the component. */
                        name?: string;
                        /**
                         * Format: int32
                         * @description Replicas specifies the number of replicas for this component.
                         */
                        replicas?: number;
                        /** @description Resources requirements for this component. */
                        resources?: {
                            /**
                             * @description Claims lists the names of resources, defined in spec.resourceClaims,
                             *     that are used by this container.
                             *
                             *     This field depends on the
                             *     DynamicResourceAllocation feature gate.
                             *
                             *     This field is immutable. It can only be set for containers.
                             */
                            claims?: {
                                /**
                                 * @description Name must match the name of one entry in pod.spec.resourceClaims of
                                 *     the Pod where this field is used. It makes that resource available
                                 *     inside a container.
                                 */
                                name: string;
                                /**
                                 * @description Request is the name chosen for a request in the referenced claim.
                                 *     If empty, everything from the claim is made available, otherwise
                                 *     only the result of this request.
                                 */
                                request?: string;
                            }[];
                            /**
                             * @description Limits describes the maximum amount of compute resources allowed.
                             *     More info: https://kubernetes.io/docs/concepts/configuration/manage-resources-containers/
                             */
                            limits?: {
                                [key: string]: number | string;
                            };
                            /**
                             * @description Requests describes the minimum amount of compute resources required.
                             *     If Requests is omitted for a container, it defaults to Limits if that is explicitly specified,
                             *     otherwise to an implementation-defined value. Requests cannot exceed Limits.
                             *     More info: https://kubernetes.io/docs/concepts/configuration/manage-resources-containers/
                             */
                            requests?: {
                                [key: string]: number | string;
                            };
                        };
                        /**
                         * @description Storage requirements for this component.
                         *     For stateless components, this is an optional field.
                         */
                        storage?: {
                            size?: number | string;
                            storageClass?: string;
                        };
                        /** @description Type of the component from the Provider. */
                        type?: string;
                        /** @description Version of the component from ComponentVersions. */
                        version?: string;
                    };
                };
                /**
                 * @description Global contains provider-level configuration that applies to the entire cluster.
                 *     The schema for this field is defined by the provider's GlobalConfigSchema.
                 */
                global?: Record<string, never>;
                /** @description Provider is the name of the database provider (e.g., "psmdb", "postgresql"). */
                provider?: string;
                /** @description Topology defines the deployment topology and its configuration. */
                topology?: {
                    /**
                     * @description Config contains topology-specific configuration.
                     *     The schema for this field is defined by the provider's TopologyDefinition.
                     *     Examples: shard count for sharded topology, replication factor, etc.
                     */
                    config?: Record<string, never>;
                    /**
                     * @description Type is the topology name (e.g., "sharded", "replicaset").
                     *     The available topologies are defined by the provider.
                     *     If omitted, the provider's default topology is used.
                     */
                    type?: string;
                };
                /**
                 * @description Version selects a provider-defined version bundle, resolving compatible
                 *     versions for all components automatically. Per-component versions set
                 *     in Components take precedence over the bundle.
                 *     If omitted and the provider defines a default bundle, that bundle is used.
                 */
                version?: string;
            };
            /** @description InstanceStatus defines the observed state of Instance. */
            status?: {
                /** @description Components is the status of the components in the database cluster. */
                components?: {
                    pods?: {
                        /**
                         * @description Name of the referent.
                         *     This field is effectively required, but due to backwards compatibility is
                         *     allowed to be empty. Instances of this type with an empty value here are
                         *     almost certainly wrong.
                         *     More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names
                         * @default
                         */
                        name: string;
                    }[];
                    /** Format: int32 */
                    ready?: number;
                    state?: string;
                    /** Format: int32 */
                    total?: number;
                }[];
                conditions?: {
                    /**
                     * Format: date-time
                     * @description lastTransitionTime is the last time the condition transitioned from one status to another.
                     *     This should be when the underlying condition changed.  If that is not known, then using the time when the API field changed is acceptable.
                     */
                    lastTransitionTime: string;
                    /**
                     * @description message is a human readable message indicating details about the transition.
                     *     This may be an empty string.
                     */
                    message: string;
                    /**
                     * Format: int64
                     * @description observedGeneration represents the .metadata.generation that the condition was set based upon.
                     *     For instance, if .metadata.generation is currently 12, but the .status.conditions[x].observedGeneration is 9, the condition is out of date
                     *     with respect to the current state of the instance.
                     */
                    observedGeneration?: number;
                    /**
                     * @description reason contains a programmatic identifier indicating the reason for the condition's last transition.
                     *     Producers of specific condition types may define expected values and meanings for this field,
                     *     and whether the values are considered a guaranteed API.
                     *     The value should be a CamelCase string.
                     *     This field may not be empty.
                     */
                    reason: string;
                    /**
                     * @description status of the condition, one of True, False, Unknown.
                     * @enum {string}
                     */
                    status: "True" | "False" | "Unknown";
                    /** @description type of condition in CamelCase or in foo.example.com/CamelCase. */
                    type: string;
                }[];
                /**
                 * @description ConnectionSecretRef is a reference to the Secret containing connection details.
                 *     The Secret is auto-generated by the provider-runtime reconciler with the name
                 *     "{instance-name}-conn" and owned by the Instance (auto-deleted on cleanup).
                 *
                 *     The Secret uses well-known keys inspired by the Service Binding specification:
                 *       - "type"     - Database type (e.g., "mongodb", "postgresql")
                 *       - "provider" - Provider name (e.g., "percona-server-mongodb")
                 *       - "host"     - Hostname or IP address
                 *       - "port"     - Port number
                 *       - "username" - Database username
                 *       - "password" - Database password
                 *       - "uri"      - Full connection URI including credentials
                 */
                connectionSecretRef?: {
                    /**
                     * @description Name of the referent.
                     *     This field is effectively required, but due to backwards compatibility is
                     *     allowed to be empty. Instances of this type with an empty value here are
                     *     almost certainly wrong.
                     *     More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names
                     * @default
                     */
                    name: string;
                };
                /**
                 * @description Phase of the database cluster.
                 * @enum {string}
                 */
                phase?: "Pending" | "Provisioning" | "Initializing" | "Ready" | "Updating" | "Terminating" | "Failed" | "Restoring" | "Suspending" | "Suspended" | "Resuming";
                /**
                 * @description Version is the effective version bundle that is currently applied to this
                 *     Instance. On the first reconciliation the provider-runtime writes the
                 *     resolved default bundle name here and uses this value on every subsequent
                 *     reconciliation when spec.version is empty. This ensures that a Provider
                 *     upgrade (which may change the default bundle) never silently triggers an
                 *     unintended database upgrade on existing Instances.
                 *
                 *     GitOps tools (ArgoCD, Flux) exclude status from diff calculations by
                 *     default, so this field does not cause spurious out-of-sync alerts.
                 */
                version?: string;
            };
        };
        /** @description ConnectionDetails holds the typed connection details for a database instance. These are written by the provider-runtime reconciler to a Kubernetes Secret and later read back by the API server to serve the connection endpoint. They follow the Service Binding well-known keys where applicable. */
        InstanceConnectionDetails: {
            /** @description Host is the hostname or IP address to connect to */
            host?: string;
            /** @description Password is the password for authentication */
            password?: string;
            /** @description Port is the port number to connect to */
            port?: string;
            /** @description Provider is the provider that manages this instance */
            provider?: string;
            /** @description Type is the type of database (e.g., mongodb, postgresql, mysql) */
            type?: string;
            /** @description URI is a pre-built connection URI */
            uri?: string;
            /** @description Username is the username for authentication */
            username?: string;
        } & {
            [key: string]: string;
        };
        /** @description InstanceList is an object that contains the list of the existing instances. */
        InstanceList: {
            /** @description APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources */
            apiVersion?: string;
            items?: components["schemas"]["Instance"][];
            /** @description Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds */
            kind?: string;
            metadata?: {
                /** @description Name must be unique within a namespace. Is required when creating resources, although some resources may allow a client to request the generation of an appropriate name automatically. Name is primarily intended for creation idempotence and configuration definition. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names#names */
                name?: string;
                /** @description Namespace defines the space within which each name must be unique. An empty namespace is equivalent to the "default" namespace, but "default" is the canonical representation. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/namespaces */
                namespace?: string;
            };
        };
        /** @description MonitoringConfig is the Schema for the monitoringconfigs API. */
        MonitoringConfig: {
            /**
             * @description APIVersion defines the versioned schema of this representation of an object.
             *     Servers should convert recognized schemas to the latest internal value, and
             *     may reject unrecognized values.
             *     More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
             */
            apiVersion?: string;
            /**
             * @description Kind is a string value representing the REST resource this object represents.
             *     Servers may infer this from the endpoint the client submits requests to.
             *     Cannot be updated.
             *     In CamelCase.
             *     More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
             */
            kind?: string;
            metadata?: Record<string, never>;
            /** @description spec defines the desired state of MonitoringConfig */
            spec: {
                /**
                 * @description CredentialsSecretName is the reference to the secret containing the API key.
                 *     It contains `apiKey` key with the API key value.
                 */
                credentialsSecretName: string;
                /**
                 * @description Type is the name of monitoring tool (e.g., "pmm").
                 * @enum {string}
                 */
                type: "pmm";
                /** @description URL is the URL of the monitoring server (e.g., PMM server URL). */
                url: string;
                /**
                 * @description VerifyTLS is set to ensure TLS/SSL verification.
                 *     If unspecified, the default value is true.
                 * @default true
                 */
                verifyTLS: boolean;
            };
            /**
             * @description status defines the observed state of MonitoringConfig
             * @default {
             *       "inUse": false
             *     }
             */
            status: {
                /**
                 * @description InUse is a flag that indicates if any Instance uses the monitoring config.
                 * @default false
                 */
                inUse: boolean;
                /**
                 * Format: int64
                 * @description LastObservedGeneration is the most recent generation observed for this MonitoringConfig.
                 */
                lastObservedGeneration?: number;
                /** @description PMMServerVersion shows PMM server version. */
                pmmServerVersion?: string;
            };
        };
        /** @description MonitoringConfigList is an object that contains the list of the existing monitoringconfigs. */
        MonitoringConfigList: {
            /** @description APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources */
            apiVersion?: string;
            items?: components["schemas"]["MonitoringConfig"][];
            /** @description Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds */
            kind?: string;
            metadata?: {
                /** @description Name must be unique within a namespace. Is required when creating resources, although some resources may allow a client to request the generation of an appropriate name automatically. Name is primarily intended for creation idempotence and configuration definition. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names#names */
                name?: string;
                /** @description Namespace defines the space within which each name must be unique. An empty namespace is equivalent to the "default" namespace, but "default" is the canonical representation. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/namespaces */
                namespace?: string;
            };
        };
        /** @description Provider is the Schema for the providers API */
        Provider: {
            /**
             * @description APIVersion defines the versioned schema of this representation of an object.
             *     Servers should convert recognized schemas to the latest internal value, and
             *     may reject unrecognized values.
             *     More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
             */
            apiVersion?: string;
            /**
             * @description Kind is a string value representing the REST resource this object represents.
             *     Servers may infer this from the endpoint the client submits requests to.
             *     Cannot be updated.
             *     In CamelCase.
             *     More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
             */
            kind?: string;
            metadata?: Record<string, never>;
            /** @description ProviderSpec defines the desired state of Provider */
            spec: {
                componentTypes?: {
                    [key: string]: {
                        versions?: {
                            default?: boolean;
                            image?: string;
                            version?: string;
                        }[];
                    };
                };
                components?: {
                    [key: string]: {
                        /** @description CustomSpecSchema holds the OpenAPI v3 schema for this component's CustomSpec. */
                        customSpecSchema?: Record<string, never>;
                        type?: string;
                    };
                };
                /** @description GlobalConfigSchema holds the OpenAPI v3 schema for the global configuration. */
                globalConfigSchema?: Record<string, never>;
                topologies?: {
                    [key: string]: {
                        components?: {
                            [key: string]: {
                                optional?: boolean;
                            };
                        };
                        /** @description ConfigSchema holds the OpenAPI v3 schema for topology-specific configuration. */
                        configSchema?: Record<string, never>;
                    };
                };
                /** @description UISchema holds the UI rendering hints for each topology. */
                uiSchema?: Record<string, never>;
                /**
                 * @description Versions defines curated version bundles — named sets of component
                 *     versions that are known to be mutually compatible. Users reference
                 *     a bundle via Instance.Spec.Version. If the user does not set a version,
                 *     the bundle whose Default field is true is used automatically.
                 */
                versions?: {
                    /**
                     * @description Components maps component names to their version strings for this bundle.
                     *     Keys must match component names defined in ProviderSpec.Components.
                     */
                    components?: {
                        [key: string]: string;
                    };
                    /**
                     * @description Default marks this bundle as the implicit choice when an Instance omits
                     *     Spec.Version entirely. Exactly one bundle should have Default: true.
                     */
                    default?: boolean;
                    /**
                     * @description Name is the unique identifier for this bundle (e.g. "8.0.12").
                     *     Users set Instance.Spec.Version to this value to select the bundle.
                     */
                    name: string;
                }[];
            };
            /** @description ProviderStatus defines the observed state of Provider. */
            status?: {
                conditions?: {
                    /**
                     * Format: date-time
                     * @description lastTransitionTime is the last time the condition transitioned from one status to another.
                     *     This should be when the underlying condition changed.  If that is not known, then using the time when the API field changed is acceptable.
                     */
                    lastTransitionTime: string;
                    /**
                     * @description message is a human readable message indicating details about the transition.
                     *     This may be an empty string.
                     */
                    message: string;
                    /**
                     * Format: int64
                     * @description observedGeneration represents the .metadata.generation that the condition was set based upon.
                     *     For instance, if .metadata.generation is currently 12, but the .status.conditions[x].observedGeneration is 9, the condition is out of date
                     *     with respect to the current state of the instance.
                     */
                    observedGeneration?: number;
                    /**
                     * @description reason contains a programmatic identifier indicating the reason for the condition's last transition.
                     *     Producers of specific condition types may define expected values and meanings for this field,
                     *     and whether the values are considered a guaranteed API.
                     *     The value should be a CamelCase string.
                     *     This field may not be empty.
                     */
                    reason: string;
                    /**
                     * @description status of the condition, one of True, False, Unknown.
                     * @enum {string}
                     */
                    status: "True" | "False" | "Unknown";
                    /** @description type of condition in CamelCase or in foo.example.com/CamelCase. */
                    type: string;
                }[];
            };
        };
        /** @description ProviderList is an object that contains the list of the existing providers. */
        ProviderList: {
            /** @description APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources */
            apiVersion?: string;
            items?: components["schemas"]["Provider"][];
            /** @description Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds */
            kind?: string;
            metadata?: {
                /** @description Name must be unique within a namespace. Is required when creating resources, although some resources may allow a client to request the generation of an appropriate name automatically. Name is primarily intended for creation idempotence and configuration definition. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names#names */
                name?: string;
            };
        };
        /** @description Restore is the Schema for the restores API. */
        Restore: {
            /**
             * @description APIVersion defines the versioned schema of this representation of an object.
             *     Servers should convert recognized schemas to the latest internal value, and
             *     may reject unrecognized values.
             *     More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
             */
            apiVersion?: string;
            /**
             * @description Kind is a string value representing the REST resource this object represents.
             *     Servers may infer this from the endpoint the client submits requests to.
             *     Cannot be updated.
             *     In CamelCase.
             *     More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
             */
            kind?: string;
            metadata?: Record<string, never>;
            /** @description RestoreSpec defines the desired state of Restore. */
            spec: {
                /**
                 * @description Config is the restore-time configuration validated against the
                 *     BackupClass's .spec.restoreConfig.openAPIV3Schema.
                 */
                config?: Record<string, never>;
                /** @description DataSource defines where the backup data to restore from is located. */
                dataSource: {
                    /**
                     * @description BackupName references an existing Backup CR in the same namespace to
                     *     restore from. The BackupClass and storage are resolved from the
                     *     referenced Backup.
                     */
                    backupName?: string;
                    /**
                     * @description External describes a backup that has no corresponding Backup CR in the
                     *     cluster (e.g., a backup taken outside of OpenEverest).
                     */
                    external?: {
                        /**
                         * @description BackupClassName is the name of the BackupClass that defines how to
                         *     restore this external backup.
                         */
                        backupClassName: string;
                        /**
                         * @description Config is forwarded to the BackupClass's restore configuration. It is
                         *     validated against the same schema as Restore.spec.config.
                         */
                        config?: Record<string, never>;
                        /**
                         * @description StorageName references the BackupStorage in the same namespace that
                         *     describes where the external backup data is located.
                         */
                        storageName: string;
                    };
                    /**
                     * @description PITR defines point-in-time recovery options. Requires the resolved
                     *     BackupClass to advertise PITR support via .spec.providerManaged.
                     */
                    pitr?: {
                        /**
                         * Format: date-time
                         * @description Date is the target recovery point in time. Required when Type is "date".
                         */
                        date?: string;
                        /**
                         * @description Type is the type of point-in-time recovery: "date" or "latest".
                         * @enum {string}
                         */
                        type: "date" | "latest";
                    };
                };
                /**
                 * @description InstanceName is the name of the Instance to restore into. The Instance
                 *     must already exist in the same namespace and use a provider listed in
                 *     the BackupClass's SupportedProviders.
                 */
                instanceName: string;
            };
            /** @description RestoreStatus defines the observed state of Restore. */
            status?: {
                /**
                 * Format: date-time
                 * @description CompletedAt is the time when the restore completed successfully.
                 */
                completedAt?: string;
                conditions?: {
                    /**
                     * Format: date-time
                     * @description lastTransitionTime is the last time the condition transitioned from one status to another.
                     *     This should be when the underlying condition changed.  If that is not known, then using the time when the API field changed is acceptable.
                     */
                    lastTransitionTime: string;
                    /**
                     * @description message is a human readable message indicating details about the transition.
                     *     This may be an empty string.
                     */
                    message: string;
                    /**
                     * Format: int64
                     * @description observedGeneration represents the .metadata.generation that the condition was set based upon.
                     *     For instance, if .metadata.generation is currently 12, but the .status.conditions[x].observedGeneration is 9, the condition is out of date
                     *     with respect to the current state of the instance.
                     */
                    observedGeneration?: number;
                    /**
                     * @description reason contains a programmatic identifier indicating the reason for the condition's last transition.
                     *     Producers of specific condition types may define expected values and meanings for this field,
                     *     and whether the values are considered a guaranteed API.
                     *     The value should be a CamelCase string.
                     *     This field may not be empty.
                     */
                    reason: string;
                    /**
                     * @description status of the condition, one of True, False, Unknown.
                     * @enum {string}
                     */
                    status: "True" | "False" | "Unknown";
                    /** @description type of condition in CamelCase or in foo.example.com/CamelCase. */
                    type: string;
                }[];
                /**
                 * @description ExecutionMode is the resolved execution mode at the time the Restore
                 *     started. Recorded for observability.
                 * @enum {string}
                 */
                executionMode?: "ProviderManaged" | "Job";
                /**
                 * @description JobName is the reference to the Job that is running the restore.
                 *     Populated only for Job classes.
                 */
                jobName?: string;
                /**
                 * Format: int64
                 * @description LastObservedGeneration is the last observed generation of the Restore CR.
                 */
                lastObservedGeneration?: number;
                /** @description Message is a human-readable message about the current state. */
                message?: string;
                /**
                 * @description OperatorRestoreRef points at the operator-native restore resource the
                 *     provider created (e.g., PerconaServerMongoDBRestore). Populated only
                 *     for ProviderManaged classes.
                 */
                operatorRestoreRef?: {
                    /**
                     * @description APIGroup is the group for the resource being referenced.
                     *     If APIGroup is not specified, the specified Kind must be in the core API group.
                     *     For any other third-party types, APIGroup is required.
                     */
                    apiGroup?: string;
                    /** @description Kind is the type of resource being referenced */
                    kind: string;
                    /** @description Name is the name of resource being referenced */
                    name: string;
                };
                /**
                 * Format: date-time
                 * @description StartedAt is the time when the restore started.
                 */
                startedAt?: string;
                /** @description State is the current state of the restore. */
                state?: string;
            };
        };
        /** @description RestoreList is an object that contains the list of the existing restores. */
        RestoreList: {
            /** @description APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources */
            apiVersion?: string;
            items?: components["schemas"]["Restore"][];
            /** @description Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds */
            kind?: string;
            metadata?: {
                /** @description Name must be unique within a namespace. Is required when creating resources, although some resources may allow a client to request the generation of an appropriate name automatically. Name is primarily intended for creation idempotence and configuration definition. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names#names */
                name?: string;
                /** @description Namespace defines the space within which each name must be unique. An empty namespace is equivalent to the "default" namespace, but "default" is the canonical representation. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/namespaces */
                namespace?: string;
            };
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
