#!/bin/bash

## ===== General environment variables for the Controller tests =====
export VICTORIAMETRICS_OPERATOR_VERSION=${VICTORIAMETRICS_OPERATOR_VERSION:-"0.66.1"}
echo "VICTORIAMETRICS_OPERATOR_VERSION=${VICTORIAMETRICS_OPERATOR_VERSION}"
