#!/bin/bash

## ===== General environment variables for the Controller tests =====
export CONTROLLER_ROOT_PATH=${CONTROLLER_ROOT_PATH:-${PWD}}
echo "CONTROLLER_ROOT_PATH=${CONTROLLER_ROOT_PATH}"

export VICTORIAMETRICS_OPERATOR_VERSION=${VICTORIAMETRICS_OPERATOR_VERSION:-"0.61.2"}
echo "VICTORIAMETRICS_OPERATOR_VERSION=${VICTORIAMETRICS_OPERATOR_VERSION}"
