version: "2"
linters:
  default: all
  disable:
    - err113
    - exhaustruct
    - godox
    - gomoddirectives
    - lll
    - mnd
    - nlreturn
    - perfsprint
    - tagalign
    - varnamelen
    - wrapcheck
    - wsl
  settings:
    cyclop:
      max-complexity: 15
    depguard:
      rules:
        main:
          files:
            - $all
            - '!$test'
          deny:
            - pkg: github.com/pkg/errors
              desc: use "errors" instead
            - pkg: github.com/gogo/protobuf/proto
              desc: use "github.com/golang/protobuf/proto" instead
    errcheck:
      exclude-functions:
        - fmt.Fprint
        - fmt.Fprintf
        - fmt.Fprintln
    unparam:
      check-exported: true
  exclusions:
    generated: lax
    rules:
      - linters:
          - funlen
          - testpackage
        path: _test\.go
    paths:
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - gci
    - gofmt
    - gofumpt
    - goimports
  settings:
    gci:
      sections:
        - standard
        - default
        - prefix(github.com/percona/everest)
    goimports:
      local-prefixes:
        - github.com/percona/everest
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
