## Append samples of your project ##
resources:
- core_v1alpha1_provider.yaml
- core_v1alpha1_instance.yaml
- backup_v1alpha1_backupclass.yaml
- backup_v1alpha1_backup.yaml
- monitoring_v1alpha1_monitoringconfig.yaml
- backup_v1alpha1_restore.yaml
# +kubebuilder:scaffold:manifestskustomizesamples
