apiVersion: core.openeverest.io/v1alpha1
kind: Provider
metadata:
  name: dummy-provider
spec:
  componentTypes:
    engine:
      versions:
        - version: "1.0.0"
          image: "dummy-operator:1.0.0"
          default: true
  components:
    engine:
      type: engine
  topologies:
    standalone:
      components:
        engine:
          optional: false
  versions:
    - name: "1.0.0"
      default: true
      components:
        engine: "1.0.0"
