apiVersion: backup.openeverest.io/v1alpha1
kind: BackupClass
metadata:
  name: dummy-backup-class
spec:
  executionMode: Job
  supportedProviders:
    - dummy-provider
  job:
    jobSpec:
      image: "dummy:1.0.0"
      command: ["echo", "backup"]
