name: FE E2E Workflow

on:
  workflow_call:
    secrets:
      CI_USER:
        required: true
      CI_PASSWORD:
        required: true
      RBAC_USER:
        required: true
      RBAC_PASSWORD:
        required: true

jobs:
  e2e:
    strategy:
      fail-fast: true
    continue-on-error: false
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v5
        with:
          lfs: true
          ref: ${{ github.event.pull_request.head.sha }}
          fetch-depth: 0

      - name: Set up Go release
        uses: actions/setup-go@v6
        with:
          go-version-file: 'go.mod'
          cache: true

      - name: Install Kubernetes tools
        uses: ./.github/actions/install-kubernetes-tools
        with:
          install-kubectl: true
          install-k3d: true

      - name: Adjust GitHub worker node
        uses: ./.github/actions/adjust-github-node
        with:
          adjust-host-for-k3d: true
          mount-docker-data: true

      - name: Create K3D test cluster
        shell: bash
        run: |
          make k3d-cluster-up

      - name: Build Everest UI
        shell: bash
        run: |
          cd ui && make init && make build EVEREST_OUT_DIR=${{ github.workspace }}/public/dist

      - name: Build Everest API Server
        shell: bash
        run: |
          CGO_ENABLED=0 GOOS=linux GOARCH=amd64 make build-debug

      - name: Build Everest docker image
        shell: bash
        run: |
          make docker-build

      - name: Upload Everest server image to K3D
        shell: bash
        run: |
          make k3d-upload-server-image

      - name: Build Everest operator docker image
        shell: bash
        run: |
          make docker-build-operator

      - name: Upload Everest operator image to K3D
        shell: bash
        run: |
          make k3d-upload-operator-image

      - name: Build CLI
        shell: bash
        run: |
          make build-cli-debug

      - name: Deploy Everest to K3D (with everest-ui namespace)
        shell: bash
        timeout-minutes: 10
        run: |
          make deploy DB_NAMESPACES=everest-ui

      - name: Adding psmdb namespace
        shell: bash
        run: |
          make add-psmdb-namespaces DB_NAMESPACES=psmdb-only

      - name: Adding pxc namespace
        shell: bash
        run: |
          make add-pxc-namespaces DB_NAMESPACES=pxc-only

      - name: Adding pg namespace
        shell: bash
        run: |
          make add-pg-namespaces DB_NAMESPACES=pg-only

      # Setup Node
      - uses: pnpm/action-setup@v4
        with:
          version: 9.4.0

      - name: Use Node
        uses: actions/setup-node@v5
        with:
          node-version: 20.x
          cache: "pnpm"
          cache-dependency-path: ui/pnpm-lock.yaml

      - name: Init test environment
        shell: bash
        working-directory: ui/apps/everest/.e2e
        timeout-minutes: 20
        run: |
          make init deploy-minio deploy-monitoring configure-rbac

      - name: Run integration tests
        shell: bash
        working-directory: ui/apps/everest/.e2e
        timeout-minutes: 30
        env:
          CI: true
        run: |
          make test

      - name: Run debug commands on failure
        if: ${{ failure() }}
        run: |
          kubectl -n everest-system describe pods
          kubectl -n everest-monitoring describe pods
          kubectl -n everest-system logs deploy/everest-server
          kubectl -n pxc-only describe pods
          kubectl -n psmdb-only describe pods
          kubectl -n pg-only describe pods

      - name: Archive report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report
          path: ui/apps/everest/.e2e/playwright-report/
          overwrite: true

